-- Seed managed service_blocks for /thg-fulfill. Generated by db/seeds/fulfill-service-blocks.ts.
-- Content mirrored VERBATIM from the merged Next landing fallback (localized-content.ts).
--
-- OWNERSHIP: this seed owns ONLY these 14 canonical roles, keyed by (page_slug,kind,payload.key):
--   journey_step: design-input, processing, quality-assurance, dispatch-ready
--   capability:   network, qc, pack, hub, intake, print, advisory
--   section_copy: consult-heading, consult-intro, hub-caption
-- It NEVER deletes page-wide: unrelated thg-fulfill blocks (pain_point, solution, policy,
-- resource, future kinds) and their translations are untouched.
--
-- POLICY = create-if-missing: a managed role is inserted only when absent, so later editor
-- edits to these roles are preserved on rerun (source-of-truth now lives in the CMS). A role
-- deleted by an editor is re-created. Idempotent: rerun is a no-op when all 14 already exist.
--
-- Each block carries payload.key (the landing binds by key, never position/order). VI lives in
-- service_blocks; EN/ZH are reviewed service_block_translations carrying the real source_hash.

-- kind: journey_step
-- role: design-input
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'journey_step', 1, 'vi', NULL, 'Design Input', 'Tiếp nhận sản phẩm & file thiết kế, gắn định danh (ID) vận hành cho từng đơn vị.', '{"key":"design-input"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='journey_step' AND locale='vi' AND json_extract(payload_json,'$.key')='design-input');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Design Input', 'Receive products and design files, assigning an operational ID to every unit.', '{"key":"design-input"}', 'reviewed', 'vi', '07617f5eade14a9b734345d5593a7e3bbecd64f3092f490cf6f33421a24131b5', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='design-input'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Design Input', '接收产品与设计文件，为每个单元分配运营ID。', '{"key":"design-input"}', 'reviewed', 'vi', '07617f5eade14a9b734345d5593a7e3bbecd64f3092f490cf6f33421a24131b5', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='design-input'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: processing
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'journey_step', 2, 'vi', NULL, 'Processing · POD', 'In POD (DTG/DTF) độ phân giải cao tại VN · CN · US.', '{"key":"processing"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='journey_step' AND locale='vi' AND json_extract(payload_json,'$.key')='processing');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Processing · POD', 'High-resolution POD printing (DTG/DTF) in Vietnam, China and the US.', '{"key":"processing"}', 'reviewed', 'vi', '94fdadba1ab2ef48af08e006680738d132c0db823eba3117cd21f01b3bea1345', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='processing'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Processing · POD', '在越南·中国·美国进行高分辨率POD打印（DTG/DTF）。', '{"key":"processing"}', 'reviewed', 'vi', '94fdadba1ab2ef48af08e006680738d132c0db823eba3117cd21f01b3bea1345', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='processing'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: quality-assurance
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'journey_step', 3, 'vi', NULL, 'Quality Assurance', 'QC từng đơn: định dạng, màu sắc, chất lượng in — chuẩn TMĐT Mỹ.', '{"key":"quality-assurance"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='journey_step' AND locale='vi' AND json_extract(payload_json,'$.key')='quality-assurance');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Quality Assurance', 'Item-level QC: file format, color and print quality — to US eCommerce standard.', '{"key":"quality-assurance"}', 'reviewed', 'vi', 'd191d92aaa0ea9fdb856f8ffd802d8fb9e1d75da1b63c14c77ecd617647ee02a', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='quality-assurance'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Quality Assurance', '逐单质检：文件格式、颜色与印刷质量——达到美国电商标准。', '{"key":"quality-assurance"}', 'reviewed', 'vi', 'd191d92aaa0ea9fdb856f8ffd802d8fb9e1d75da1b63c14c77ecd617647ee02a', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='quality-assurance'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: dispatch-ready
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'journey_step', 4, 'vi', NULL, 'Dispatch Ready', 'Đóng gói chuẩn quy cách, dán nhãn vận chuyển + tracking.', '{"key":"dispatch-ready"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='journey_step' AND locale='vi' AND json_extract(payload_json,'$.key')='dispatch-ready');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Dispatch Ready', 'Standards-compliant packing with a shipping label and tracking.', '{"key":"dispatch-ready"}', 'reviewed', 'vi', '175c82c6ecf01e1140a302e39d89ab6e10e6fa4e7228c27a995b1d575c05f8ea', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='dispatch-ready'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Dispatch Ready', '按规范包装，贴运输标签并提供追踪。', '{"key":"dispatch-ready"}', 'reviewed', 'vi', '175c82c6ecf01e1140a302e39d89ab6e10e6fa4e7228c27a995b1d575c05f8ea', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='journey_step' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='dispatch-ready'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- kind: capability
-- role: network
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 1, 'vi', NULL, 'Cross-border network', 'Xưởng POD tại VN · CN và fulfill nội địa US — định tuyến theo sản phẩm & điểm đến.', '{"key":"network"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='network');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Cross-border network', 'POD workshops in VN · CN and US domestic fulfillment — routed by product and destination.', '{"key":"network"}', 'reviewed', 'vi', '19603555265abeb41a9dbfcb7e04110d439b8d88928db8394ce1f48f65f91f65', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='network'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Cross-border network', '越南·中国的POD车间与美国本土履约——按产品与目的地路由。', '{"key":"network"}', 'reviewed', 'vi', '19603555265abeb41a9dbfcb7e04110d439b8d88928db8394ce1f48f65f91f65', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='network'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: qc
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 2, 'vi', NULL, 'Item-level QC', 'Kiểm tra chất lượng từng đơn trước khi đóng gói.', '{"key":"qc"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='qc');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Item-level QC', 'Quality-checking every order before it is packed.', '{"key":"qc"}', 'reviewed', 'vi', '7a8ecc4871e1bb03a3b793770b0acaa58ef210a54579a8ba5e0374f3bc44ca18', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='qc'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Item-level QC', '在包装前检查每一个订单的质量。', '{"key":"qc"}', 'reviewed', 'vi', '7a8ecc4871e1bb03a3b793770b0acaa58ef210a54579a8ba5e0374f3bc44ca18', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='qc'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: pack
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 3, 'vi', NULL, 'Đóng gói chuẩn Mỹ', 'Đóng gói chuẩn TMĐT Mỹ, dán nhãn + tracking.', '{"key":"pack"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='pack');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'US standard packing', 'US eCommerce-standard packing with label and tracking.', '{"key":"pack"}', 'reviewed', 'vi', '8d5429299b10f04c29ee6b83ae58580582a9e04d2adf434f9c0e05f30f302644', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='pack'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'US standard packing', '美国电商标准包装，附标签与追踪。', '{"key":"pack"}', 'reviewed', 'vi', '8d5429299b10f04c29ee6b83ae58580582a9e04d2adf434f9c0e05f30f302644', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='pack'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: hub
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 4, 'vi', NULL, 'Hub System', 'Trạng thái đơn hàng & sản phẩm hiển thị theo từng bước — không cần dò file thủ công.', '{"key":"hub"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='hub');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Hub System', 'Order and product status visible step by step — no manual file digging.', '{"key":"hub"}', 'reviewed', 'vi', '0c36fb54158130fb18958178cfcbe123b67d1a3fdc7b7a785e8a221bd920c244', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='hub'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Hub System', '订单与产品状态按步骤可见——无需手动翻查文件。', '{"key":"hub"}', 'reviewed', 'vi', '0c36fb54158130fb18958178cfcbe123b67d1a3fdc7b7a785e8a221bd920c244', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='hub'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: intake
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 5, 'vi', NULL, 'Tiếp nhận & định danh', 'Tiếp nhận sản phẩm & file, gắn định danh vận hành.', '{"key":"intake"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='intake');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Intake & ID', 'Receiving products and files, assigning an operational ID.', '{"key":"intake"}', 'reviewed', 'vi', '8d0148ed56b396020d01eedfad111b8946529caa5c5d267fe7bb5c3ca4d5d1d1', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='intake'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Intake & ID', '接收产品与文件，分配运营标识。', '{"key":"intake"}', 'reviewed', 'vi', '8d0148ed56b396020d01eedfad111b8946529caa5c5d267fe7bb5c3ca4d5d1d1', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='intake'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: print
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 6, 'vi', NULL, 'POD & cá nhân hóa', 'In DTG/DTF độ phân giải cao theo yêu cầu.', '{"key":"print"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='print');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'POD & personalization', 'High-resolution DTG/DTF printing on demand.', '{"key":"print"}', 'reviewed', 'vi', '121489680b5131c44d399a5415b6329e67a5f5dc5db8fb4bbd77cc5d8623153a', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='print'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'POD & personalization', '按需高分辨率DTG/DTF打印。', '{"key":"print"}', 'reviewed', 'vi', '121489680b5131c44d399a5415b6329e67a5f5dc5db8fb4bbd77cc5d8623153a', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='print'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: advisory
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'capability', 7, 'vi', NULL, 'Tư vấn', 'Tư vấn theo loại sản phẩm và nhu cầu cụ thể.', '{"key":"advisory"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='capability' AND locale='vi' AND json_extract(payload_json,'$.key')='advisory');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Consultation', 'Advice tailored to your product type and specific needs.', '{"key":"advisory"}', 'reviewed', 'vi', '17448fe3850b7c2bca655f4523c83328f3eef609e2c32b44c0732dc48487a112', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='advisory'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', 'Consultation', '根据您的产品类型与具体需求提供咨询。', '{"key":"advisory"}', 'reviewed', 'vi', '17448fe3850b7c2bca655f4523c83328f3eef609e2c32b44c0732dc48487a112', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='capability' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='advisory'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- kind: section_copy
-- role: consult-heading
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'section_copy', 1, 'vi', NULL, 'Mở hồ sơ vận hành.', '', '{"key":"consult-heading"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='section_copy' AND locale='vi' AND json_extract(payload_json,'$.key')='consult-heading');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', 'Open an operations file.', '', '{"key":"consult-heading"}', 'reviewed', 'vi', '1a862cc38d09bcf2339577d01a48f2583628317e282eeb6b63a052ae94bd2c64', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='consult-heading'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', '开启运营档案。', '', '{"key":"consult-heading"}', 'reviewed', 'vi', '1a862cc38d09bcf2339577d01a48f2583628317e282eeb6b63a052ae94bd2c64', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='consult-heading'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: consult-intro
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'section_copy', 2, 'vi', NULL, '', 'Không cấp báo giá tự động. Mô tả sản phẩm và nhu cầu — đội ngũ THG sẽ thiết kế luồng vận hành phù hợp và liên hệ trực tiếp.', '{"key":"consult-intro"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='section_copy' AND locale='vi' AND json_extract(payload_json,'$.key')='consult-intro');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', '', 'No automated quotes. Describe your product and needs — the THG team designs the right operational flow and contacts you directly.', '{"key":"consult-intro"}', 'reviewed', 'vi', '4c52db64a5dffa52ef9a5e1ef49493786f5762ea9e4f4aa7844010c0b7547118', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='consult-intro'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', '', '不提供自动报价。描述您的产品与需求——THG团队将设计合适的运营流程并直接联系您。', '{"key":"consult-intro"}', 'reviewed', 'vi', '4c52db64a5dffa52ef9a5e1ef49493786f5762ea9e4f4aa7844010c0b7547118', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='consult-intro'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

-- role: hub-caption
INSERT INTO service_blocks (page_slug, kind, position, locale, icon, title, description, payload_json)
SELECT 'thg-fulfill', 'section_copy', 3, 'vi', NULL, '', 'Hub System hiển thị trạng thái theo từng bước xử lý cho đội vận hành của bạn.', '{"key":"hub-caption"}'
WHERE NOT EXISTS (SELECT 1 FROM service_blocks WHERE page_slug='thg-fulfill' AND kind='section_copy' AND locale='vi' AND json_extract(payload_json,'$.key')='hub-caption');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'en', '', 'Hub System surfaces status at each processing stage for your operations team.', '{"key":"hub-caption"}', 'reviewed', 'vi', '451e2448858d317e97a34cfee76666832f7fc0956a7492cae4fb928947695050', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='hub-caption'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='en');
INSERT INTO service_block_translations (service_block_id, locale, title, description, payload_json, status, source_locale, source_hash, reviewed_at)
SELECT vi.id, 'zh', '', 'Hub System 在每个处理阶段向您的运营团队显示状态。', '{"key":"hub-caption"}', 'reviewed', 'vi', '451e2448858d317e97a34cfee76666832f7fc0956a7492cae4fb928947695050', unixepoch()
FROM service_blocks vi
WHERE vi.page_slug='thg-fulfill' AND vi.kind='section_copy' AND vi.locale='vi' AND json_extract(vi.payload_json,'$.key')='hub-caption'
  AND NOT EXISTS (SELECT 1 FROM service_block_translations t WHERE t.service_block_id=vi.id AND t.locale='zh');

