// Bootstrap pricing tables from THG_landingpage/src/data/pricingData.ts → SQL.
// Run: bun run scripts/bootstrap-pricing.ts
// Then: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-pricing.sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(
  process.cwd(),
  "..",
  "THG_landingpage",
  "src",
  "data",
  "pricingData.ts",
);
const OUT = resolve(process.cwd(), "scripts", ".tmp-bootstrap-pricing.sql");

// Friendly names for known table slugs (admin UI displays this).
const NAMES: Record<string, string> = {
  vnThuongMeta: "VN Thường — ETA",
  vnThuong: "VN Thường — Bảng giá theo kg",
  vnMyphamMeta: "VN Mỹ phẩm — ETA",
  vnMypham: "VN Mỹ phẩm — Bảng giá",
  uspsCn: "USPS CN tuyến nội địa",
  uspsCnUs: "USPS CN→US",
  cnThuongMeta: "CN Thường — ETA",
  cnThuong: "CN Thường — Bảng giá",
  cnMyphamMeta: "CN Mỹ phẩm — ETA",
  cnMypham: "CN Mỹ phẩm — Bảng giá",
  cnPinMeta: "CN hàng pin — ETA",
  cnPin: "CN hàng pin — Bảng giá",
  tiktokCnUsNormal: "TikTok CN→US thường",
  tiktokCnUsSpecial: "TikTok CN→US đặc biệt",
  expressVnUs: "Express VN→US",
  expressCnUs: "Express CN→US",
  euRate: "Tỷ giá EU",
  redelivery: "Phụ phí giao lại",
};

function escapeSqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function extractPricingObject(source: string): Record<string, unknown> {
  const startMarker = "export const pricingData: Record<string, any> = {";
  const start = source.indexOf(startMarker);
  if (start < 0) throw new Error("Cannot find `export const pricingData` in source.");
  const objStart = source.indexOf("{", start);

  let depth = 0;
  let i = objStart;
  let inStr = false;
  let strQuote = "";
  while (i < source.length) {
    const ch = source[i];
    const prev = source[i - 1];
    if (inStr) {
      if (ch === strQuote && prev !== "\\") inStr = false;
    } else {
      if (ch === '"' || ch === "'" || ch === "`") {
        inStr = true;
        strQuote = ch;
      } else if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }
  if (depth !== 0) throw new Error("Could not find matching closing brace.");

  const objLiteral = source.slice(objStart, i + 1);
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  const fn = new Function(`return (${objLiteral});`);
  return fn() as Record<string, unknown>;
}

function detectKind(value: unknown): "weight_grid" | "meta_kv" {
  if (Array.isArray(value)) return "weight_grid";
  return "meta_kv";
}

function inferSchema(value: unknown, kind: "weight_grid" | "meta_kv"): unknown {
  if (kind === "meta_kv") {
    return { type: "meta_kv", description: "Country code → ETA string" };
  }
  // weight_grid: union of all keys across rows
  const rows = value as Array<Record<string, unknown>>;
  const colSet = new Set<string>();
  for (const row of rows) {
    for (const key of Object.keys(row)) colSet.add(key);
  }
  const columns = Array.from(colSet).map((code, idx) => ({
    code,
    label: code === "kg" ? "Kg" : code.toUpperCase(),
    position: idx,
    type: code === "kg" ? "number" : "currency",
  }));
  return { type: "weight_grid", columns };
}

async function main() {
  const { readFile } = await import("node:fs/promises");
  const source = await readFile(SOURCE, "utf8");
  const pricing = extractPricingObject(source);

  const lines: string[] = [
    "-- Generated by scripts/bootstrap-pricing.ts. Idempotent (UPSERT on slug).",
    "BEGIN TRANSACTION;",
  ];

  let count = 0;
  for (const [slug, value] of Object.entries(pricing)) {
    const kind = detectKind(value);
    const name = NAMES[slug] ?? slug;
    const schema = inferSchema(value, kind);
    const dataJson = JSON.stringify(value);
    const schemaJson = JSON.stringify(schema);

    lines.push(
      `INSERT INTO pricing_tables(slug, name, kind, schema_json, data_json, version, status, updated_at) ` +
        `VALUES(${escapeSqlString(slug)}, ${escapeSqlString(name)}, ${escapeSqlString(kind)}, ` +
        `${escapeSqlString(schemaJson)}, ${escapeSqlString(dataJson)}, 1, 'live', unixepoch()) ` +
        `ON CONFLICT(slug) DO UPDATE SET ` +
        `name=excluded.name, kind=excluded.kind, schema_json=excluded.schema_json, ` +
        `data_json=excluded.data_json, updated_at=unixepoch();`,
    );
    count++;
  }

  lines.push("COMMIT;");
  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");

  console.log(`✓ Extracted ${count} pricing tables`);
  console.log(`✓ Wrote SQL to ${OUT}`);
  console.log("");
  console.log("Apply locally:");
  console.log("  bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-pricing.sql");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
