// Bootstrap careers_jobs from THG_landingpage data (CareersPage.tsx + careers_i18n.ts) → SQL.
// Run: bun run scripts/bootstrap-careers.ts
// Then: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-careers.sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const CAREERS_PAGE = resolve(process.cwd(), "..", "THG_landingpage", "src", "pages", "CareersPage.tsx");
const I18N_FILE = resolve(process.cwd(), "..", "THG_landingpage", "src", "data", "careers_i18n.ts");
const OUT = resolve(process.cwd(), "scripts", ".tmp-bootstrap-careers.sql");

function escapeSql(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Extract a top-level array/object literal from source by name + delimiter.
function extractLiteral(source: string, marker: string): unknown {
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`Cannot find marker "${marker}"`);
  // Find first [ or { after the marker
  let objStart = -1;
  for (let i = start + marker.length; i < source.length; i++) {
    if (source[i] === "[" || source[i] === "{") { objStart = i; break; }
  }
  if (objStart < 0) throw new Error(`Cannot find opening bracket after "${marker}"`);

  const openCh = source[objStart];
  const closeCh = openCh === "[" ? "]" : "}";

  let depth = 0;
  let i = objStart;
  let inStr = false;
  let strQuote = "";
  while (i < source.length) {
    const ch = source[i];
    const prev = source[i - 1];
    if (inStr) {
      if (ch === strQuote && prev !== "\\") inStr = false;
    } else {
      if (ch === '"' || ch === "'" || ch === "`") {
        inStr = true;
        strQuote = ch;
      } else if (ch === openCh) depth++;
      else if (ch === closeCh) {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }
  const literal = source.slice(objStart, i + 1);
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  return new Function(`return (${literal});`)();
}

interface RichI18n {
  responsibilities?: Record<string, string[]>;
  requirements?: string[];
  benefits?: Array<{ i?: string; t: string; d: string }>;
  bonuses?: string[];
}

interface Job {
  id: string; cat: string; filter: string; hot?: boolean;
  badge: string; tagline: string; title: string; desc: string;
  salary: string; salaryUnit: string; salaryNote: string;
  location: string; type: string; deadline: string; experience: string;
  lead: string;
  responsibilities: Record<string, string[]>;
  requirements: string[];
  benefits: Array<{ i: string; t: string; d: string }>;
  bonuses: string[];
}

async function main() {
  const fs = await import("node:fs/promises");
  const careersSrc = await fs.readFile(CAREERS_PAGE, "utf8");
  const i18nSrc = await fs.readFile(I18N_FILE, "utf8");

  const JOBS = extractLiteral(careersSrc, "const JOBS: Job[] = ") as Job[];
  const I18N = extractLiteral(i18nSrc, "export const CAREERS_JOBS_I18N: Record<string, any> = ") as Record<string, Record<string, RichI18n>>;

  const sql: string[] = [
    "-- Bootstrap careers_jobs (auto-generated by bootstrap-careers.ts)",
    "-- Cleans existing rows + inserts 7 jobs × 3 locales = 21 rows.",
    "DELETE FROM careers_jobs;",
    "",
  ];

  for (let position = 0; position < JOBS.length; position++) {
    const job = JOBS[position];
    const richByLocale = I18N[job.id] ?? {};

    for (const locale of ["en", "vi", "zh"] as const) {
      // Title / surface fields: Vietnamese values shared across locales
      // (operator can override per-locale via admin later).
      const title = job.title;
      const tagline = job.tagline;
      const lead = job.lead;
      const desc = job.desc;
      const salary = job.salary;
      const salaryUnit = job.salaryUnit;
      const salaryNote = job.salaryNote;
      const location = job.location;
      const type = job.type;
      const deadline = job.deadline;
      const experience = job.experience;
      const badge = job.badge;
      const category = job.cat;

      // Rich fields: prefer locale-specific from I18N, fall back to base JOBS (vi).
      const rich = richByLocale[locale];
      const responsibilities = rich?.responsibilities ?? job.responsibilities;
      const requirements = rich?.requirements ?? job.requirements;
      const benefits = rich?.benefits
        ? rich.benefits.map((b, i) => ({
            i: b.i ?? job.benefits[i]?.i ?? "🏆",
            t: b.t,
            d: b.d,
          }))
        : job.benefits;
      const bonuses = rich?.bonuses ?? job.bonuses;

      sql.push(
        `INSERT INTO careers_jobs (slug, locale, position, title, body_md, location, employment_type, status, posted_at, category, hot, badge, tagline, salary, salary_unit, salary_note, deadline, experience, lead, responsibilities_json, requirements_json, benefits_json, bonuses_json)`,
        `  VALUES (${escapeSql(job.id)}, ${escapeSql(locale)}, ${position}, ${escapeSql(title)}, ${escapeSql(desc)}, ${escapeSql(location)}, ${escapeSql(type)}, 'open', unixepoch(), ${escapeSql(category)}, ${job.hot ? 1 : 0}, ${escapeSql(badge)}, ${escapeSql(tagline)}, ${escapeSql(salary)}, ${escapeSql(salaryUnit)}, ${escapeSql(salaryNote)}, ${escapeSql(deadline)}, ${escapeSql(experience)}, ${escapeSql(lead)}, ${escapeSql(JSON.stringify(responsibilities))}, ${escapeSql(JSON.stringify(requirements))}, ${escapeSql(JSON.stringify(benefits))}, ${escapeSql(JSON.stringify(bonuses))});`,
        "",
      );
    }
  }

  writeFileSync(OUT, sql.join("\n"), "utf8");
  console.log(`✓ Wrote ${OUT} (${JOBS.length} jobs × 3 locales)`);
  console.log(`Next: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-careers.sql`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
