// Bootstrap policies from THG_landingpage/src/data/policyData.ts → SQL.
// 5 sections × 3 locales = 15 rows (mode='image', image_list_json populated).

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(process.cwd(), "..", "THG_landingpage", "src", "data", "policyData.ts");
const OUT = resolve(process.cwd(), "scripts", ".tmp-bootstrap-policies.sql");

function escapeSql(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function extractLiteral(source: string, marker: string): unknown {
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`Cannot find marker "${marker}"`);
  let objStart = -1;
  for (let i = start + marker.length; i < source.length; i++) {
    if (source[i] === "[" || source[i] === "{") { objStart = i; break; }
  }
  if (objStart < 0) throw new Error(`Cannot find opening bracket after "${marker}"`);
  const openCh = source[objStart];
  const closeCh = openCh === "[" ? "]" : "}";

  let depth = 0;
  let i = objStart;
  let inStr = false;
  let strQuote = "";
  while (i < source.length) {
    const ch = source[i];
    const prev = source[i - 1];
    if (inStr) {
      if (ch === strQuote && prev !== "\\") inStr = false;
    } else {
      if (ch === '"' || ch === "'" || ch === "`") {
        inStr = true;
        strQuote = ch;
      } else if (ch === openCh) depth++;
      else if (ch === closeCh) {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }
  const literal = source.slice(objStart, i + 1);
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  return new Function(`const BASE = "https://w.ladicdn.com/s1300x950/67e69e24e8a7ba001127c80a"; return (${literal});`)();
}

interface PolicySection {
  id: string;
  title: string;
  titleKey: string;
  icon: string;
  images: string[];
}

async function main() {
  const fs = await import("node:fs/promises");
  const src = await fs.readFile(SOURCE, "utf8");
  const sections = extractLiteral(src, "export const policySections: PolicySection[] = ") as PolicySection[];

  const sql: string[] = [
    "-- Bootstrap policies (auto-generated by bootstrap-policies.ts)",
    "DELETE FROM policies;",
    "",
  ];

  // For VI use original Vietnamese titles; for EN/ZH copy same images but title translated stub.
  // Operator can later edit per locale via admin.
  const titlesByLocale: Record<string, Record<string, string>> = {
    "warehouse": { en: "Warehouse Policy", vi: "Chính sách Warehouse", zh: "仓储政策" },
    "pod-dropship": { en: "POD / Dropship Policy", vi: "Chính sách POD / Dropship", zh: "POD/代发政策" },
    "shipping": { en: "Shipping Policy", vi: "Chính sách Vận chuyển", zh: "运输政策" },
    "compensation": { en: "Compensation Policy", vi: "Chính sách đền bù hàng lô", zh: "批量货物赔偿政策" },
    "tiktok": { en: "POD - TikTok Shipping", vi: "POD - TikTok Shipping", zh: "POD - TikTok运输" },
  };

  for (let position = 0; position < sections.length; position++) {
    const sec = sections[position];
    const titleMap = titlesByLocale[sec.id] ?? { en: sec.title, vi: sec.title, zh: sec.title };

    for (const locale of ["en", "vi", "zh"] as const) {
      sql.push(
        `INSERT INTO policies (slug, locale, title, body_md, version, updated_at, icon, mode, image_list_json, summary, position)`,
        `  VALUES (${escapeSql(sec.id)}, ${escapeSql(locale)}, ${escapeSql(titleMap[locale])}, '', 1, unixepoch(), ${escapeSql(sec.icon)}, 'image', ${escapeSql(JSON.stringify(sec.images))}, NULL, ${position});`,
        "",
      );
    }
  }

  writeFileSync(OUT, sql.join("\n"), "utf8");
  console.log(`✓ Wrote ${OUT} (${sections.length} sections × 3 locales = ${sections.length * 3} rows)`);
  console.log(`Next: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-policies.sql`);
}

main().catch((err) => { console.error(err); process.exit(1); });
