// Bootstrap shipping_routes — seeds 7 route shells × 3 locales as DRAFT.
// Status='draft' so landing falls back to hardcoded 7 Route*.tsx components
// until operator fills body_md/tables via admin then sets status='live'.

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(process.cwd(), "scripts", ".tmp-bootstrap-shipping.sql");

interface RouteSeed {
  slug: string;
  origin: string;
  destination: string;
  kind: string;
  position: number;
  titles: { en: string; vi: string; zh: string };
}

const ROUTES: RouteSeed[] = [
  {
    slug: "vn-us-regular", origin: "VN", destination: "US", kind: "regular", position: 0,
    titles: {
      en: "Vietnam → USA · Standard",
      vi: "Việt Nam → Mỹ · Hàng thường",
      zh: "越南 → 美国 · 标准",
    },
  },
  {
    slug: "vn-us-cosmetics", origin: "VN", destination: "US", kind: "cosmetics", position: 1,
    titles: {
      en: "Vietnam → USA · Cosmetics",
      vi: "Việt Nam → Mỹ · Mỹ phẩm",
      zh: "越南 → 美国 · 化妆品",
    },
  },
  {
    slug: "cn-us-regular", origin: "CN", destination: "US", kind: "regular", position: 2,
    titles: {
      en: "China → USA · Standard",
      vi: "Trung Quốc → Mỹ · Hàng thường",
      zh: "中国 → 美国 · 标准",
    },
  },
  {
    slug: "cn-us-cosmetics", origin: "CN", destination: "US", kind: "cosmetics", position: 3,
    titles: {
      en: "China → USA · Cosmetics",
      vi: "Trung Quốc → Mỹ · Mỹ phẩm",
      zh: "中国 → 美国 · 化妆品",
    },
  },
  {
    slug: "cn-us-batteries", origin: "CN", destination: "US", kind: "batteries", position: 4,
    titles: {
      en: "China → USA · Batteries",
      vi: "Trung Quốc → Mỹ · Hàng pin",
      zh: "中国 → 美国 · 电池",
    },
  },
  {
    slug: "vn-us-priority", origin: "VN", destination: "US,DE", kind: "priority", position: 5,
    titles: {
      en: "Vietnam → USA & Germany · Priority",
      vi: "Việt Nam → Mỹ & Đức · Priority",
      zh: "越南 → 美国 & 德国 · Priority",
    },
  },
  {
    slug: "cn-us-priority", origin: "CN", destination: "US,DE", kind: "priority", position: 6,
    titles: {
      en: "China → USA & Germany · Priority",
      vi: "Trung Quốc → Mỹ & Đức · Priority",
      zh: "中国 → 美国 & 德国 · Priority",
    },
  },
];

function escapeSql(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function main() {
  const sql: string[] = [
    "-- Bootstrap shipping_routes (auto-generated by bootstrap-shipping.ts)",
    "-- Status='draft' — landing keeps using hardcoded Route*.tsx fallback until operator promotes to 'live'.",
    "DELETE FROM shipping_routes;",
    "",
  ];

  for (const r of ROUTES) {
    for (const locale of ["en", "vi", "zh"] as const) {
      sql.push(
        `INSERT INTO shipping_routes (slug, locale, position, title, origin, destination, kind, body_md, notes_json, status, updated_at)`,
        `  VALUES (${escapeSql(r.slug)}, ${escapeSql(locale)}, ${r.position}, ${escapeSql(r.titles[locale])}, ${escapeSql(r.origin)}, ${escapeSql(r.destination)}, ${escapeSql(r.kind)}, '', NULL, 'draft', unixepoch());`,
        "",
      );
    }
  }

  writeFileSync(OUT, sql.join("\n"), "utf8");
  console.log(`✓ Wrote ${OUT} (${ROUTES.length} routes × 3 locales = ${ROUTES.length * 3} rows)`);
  console.log(`Next: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-bootstrap-shipping.sql`);
}

main();
