// Migrate blog articles from THG_landingpage/src/data/blogData.ts → D1.
// Each article has title/excerpt × 3 locales = 1 blog_posts row × 3 locales,
// + thumbnail + N slides, each becoming a media row + blog_slides link.
//
// Run: bun run scripts/migrate-blog.ts
// Then: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-blog.sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(
  process.cwd(),
  "..",
  "THG_landingpage",
  "src",
  "data",
  "blogData.ts",
);
const OUT = resolve(process.cwd(), "scripts", ".tmp-migrate-blog.sql");

interface BlogArticle {
  id: string;
  slug: string;
  category: string;
  date: string;
  month: string;
  title: { en: string; vi: string; zh: string };
  excerpt: { en: string; vi: string; zh: string };
  thumbnail: string;
  slides: string[];
  featured?: boolean;
}

function escapeSqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function extractArray(source: string): BlogArticle[] {
  const marker = "export const blogArticles: BlogArticle[] = [";
  const start = source.indexOf(marker);
  if (start < 0) throw new Error("Cannot find blogArticles export");
  // The opening `[` of the array literal is at `start + marker.length - 1`
  // (the marker includes the `[`). Move past `BlogArticle[]` type annotation.
  const arrStart = start + marker.length - 1;
  let depth = 0, i = arrStart, inStr = false, q = "";
  while (i < source.length) {
    const ch = source[i], prev = source[i - 1];
    if (inStr) {
      if (ch === q && prev !== "\\") inStr = false;
    } else {
      if (ch === '"' || ch === "'" || ch === "`") { inStr = true; q = ch; }
      else if (ch === "[") depth++;
      else if (ch === "]") { depth--; if (depth === 0) break; }
    }
    i++;
  }
  const lit = source.slice(arrStart, i + 1);
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  return new Function(`return (${lit});`)() as BlogArticle[];
}

async function main() {
  const { readFile } = await import("node:fs/promises");
  const source = await readFile(SOURCE, "utf8");
  const articles = extractArray(source);

  const lines: string[] = [
    "-- Generated by scripts/migrate-blog.ts. Idempotent (cleans + reinserts).",
    "BEGIN TRANSACTION;",
    "DELETE FROM blog_slides;",
    "DELETE FROM blog_posts;",
    "DELETE FROM media WHERE r2_key LIKE 'https://w.ladicdn.com/%' AND id NOT IN (SELECT media_id FROM marquee_images);",
    "",
  ];

  let blogCount = 0;
  let mediaCount = 0;
  let slideCount = 0;
  const seenUrls = new Set<string>(); // dedupe media inserts (slide[0] often == thumbnail)

  function emitMediaRow(url: string, alt: string) {
    if (seenUrls.has(url)) return;
    seenUrls.add(url);
    lines.push(
      `INSERT INTO media(r2_key, mime, bytes, alt_text, status) VALUES(${escapeSqlString(url)}, 'image/png', 0, ${escapeSqlString(alt)}, 'ready');`,
    );
    mediaCount++;
  }

  for (const article of articles) {
    emitMediaRow(article.thumbnail, `Thumbnail: ${article.title.en}`);
    const thumbnailVar = `(SELECT id FROM media WHERE r2_key = ${escapeSqlString(article.thumbnail)} LIMIT 1)`;

    for (const locale of ["en", "vi", "zh"] as const) {
      lines.push(
        `INSERT INTO blog_posts(slug, locale, title, excerpt, thumbnail_media_id, category, published_date, status, updated_at) ` +
          `VALUES(${escapeSqlString(article.slug)}, ${escapeSqlString(locale)}, ${escapeSqlString(article.title[locale])}, ${escapeSqlString(article.excerpt[locale])}, ${thumbnailVar}, ${escapeSqlString(article.category)}, ${escapeSqlString(article.date)}, 'live', unixepoch());`,
      );
      blogCount++;
    }

    const postEnVar = `(SELECT id FROM blog_posts WHERE slug = ${escapeSqlString(article.slug)} AND locale = 'en' LIMIT 1)`;

    article.slides.forEach((url, idx) => {
      emitMediaRow(url, `${article.title.en} — slide ${idx + 1}`);
      const mediaVar = `(SELECT id FROM media WHERE r2_key = ${escapeSqlString(url)} LIMIT 1)`;
      lines.push(
        `INSERT INTO blog_slides(post_id, position, media_id, alt_text) ` +
          `VALUES(${postEnVar}, ${idx + 1}, ${mediaVar}, ${escapeSqlString(`${article.title.en} — slide ${idx + 1}`)});`,
      );
      slideCount++;
    });
    lines.push("");
  }

  lines.push("COMMIT;");
  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");

  console.log(`✓ Articles: ${articles.length} × 3 locales = ${blogCount} blog_posts rows`);
  console.log(`✓ Media: ${mediaCount} rows (thumbnails + slides, external URLs)`);
  console.log(`✓ Slides: ${slideCount} rows`);
  console.log(`✓ Wrote SQL to ${OUT}`);
  console.log("");
  console.log("Apply locally:");
  console.log("  bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-blog.sql");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
