// Extract translations from THG_landingpage/src/lib/i18n.tsx → SQL.
// Run: bun run scripts/migrate-i18n.ts
// Then: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-i18n.sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(
  process.cwd(),
  "..",
  "THG_landingpage",
  "src",
  "lib",
  "i18n.tsx",
);
const OUT = resolve(process.cwd(), "scripts", ".tmp-migrate-i18n.sql");

type Translations = Record<string, Record<"en" | "vi" | "zh", string>>;

function escapeSqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function extractTranslationsObject(source: string): Translations {
  const startMarker = "const translations: Translations = {";
  const start = source.indexOf(startMarker);
  if (start < 0) throw new Error("Cannot find `const translations: Translations = {` in source.");
  const objStart = source.indexOf("{", start);

  // Walk forward, count brace depth, ignore braces inside strings.
  let depth = 0;
  let i = objStart;
  let inStr = false;
  let strQuote = "";
  while (i < source.length) {
    const ch = source[i];
    const prev = source[i - 1];
    if (inStr) {
      if (ch === strQuote && prev !== "\\") inStr = false;
    } else {
      if (ch === '"' || ch === "'" || ch === "`") {
        inStr = true;
        strQuote = ch;
      } else if (ch === "{") depth++;
      else if (ch === "}") {
        depth--;
        if (depth === 0) break;
      }
    }
    i++;
  }
  if (depth !== 0) throw new Error("Could not find matching closing brace for translations object.");

  const objLiteral = source.slice(objStart, i + 1);
  // Trusted local source file from the same project — eval is acceptable here.
  // eslint-disable-next-line @typescript-eslint/no-implied-eval
  const fn = new Function(`return (${objLiteral});`);
  return fn() as Translations;
}

async function main() {
  const { readFile } = await import("node:fs/promises");
  const source = await readFile(SOURCE, "utf8");

  const translations = extractTranslationsObject(source);

  const lines: string[] = [
    "-- Generated by scripts/migrate-i18n.ts. Idempotent (UPSERT on PK).",
    "BEGIN TRANSACTION;",
  ];

  let count = 0;
  for (const [key, byLocale] of Object.entries(translations)) {
    for (const locale of ["en", "vi", "zh"] as const) {
      const value = byLocale[locale];
      if (value === undefined || value === null) continue;
      lines.push(
        `INSERT INTO translations(key, locale, value, updated_at) ` +
          `VALUES(${escapeSqlString(key)}, ${escapeSqlString(locale)}, ${escapeSqlString(value)}, unixepoch()) ` +
          `ON CONFLICT(key, locale) DO UPDATE SET value=excluded.value, updated_at=unixepoch();`,
      );
      count++;
    }
  }

  lines.push("COMMIT;");

  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");

  console.log(`✓ Extracted ${Object.keys(translations).length} keys → ${count} translation rows`);
  console.log(`✓ Wrote SQL to ${OUT}`);
  console.log("");
  console.log("Apply locally:");
  console.log("  bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-i18n.sql");
  console.log("");
  console.log("Apply to production D1:");
  console.log("  bunx wrangler d1 execute thg-cms --remote --env production --file=scripts/.tmp-migrate-i18n.sql");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
