// Seed the D1 `translations` table from the landing repo's static dictionary
// (imported from THG_landingpage/src/lib/i18n/translations/) → SQL.
// Run: bun run scripts/migrate-i18n.ts
// Then: bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-i18n.sql

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { loadLandingTranslations } from "./lib/loadLandingTranslations";

const OUT = resolve(process.cwd(), "scripts", ".tmp-migrate-i18n.sql");

function escapeSqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

async function main() {
  const translations = await loadLandingTranslations();

  const lines: string[] = [
    "-- Generated by scripts/migrate-i18n.ts. Idempotent (UPSERT on PK).",
    "BEGIN TRANSACTION;",
  ];

  let count = 0;
  for (const [key, byLocale] of Object.entries(translations)) {
    for (const locale of ["en", "vi", "zh"] as const) {
      const value = byLocale[locale];
      if (value === undefined || value === null) continue;
      lines.push(
        `INSERT INTO translations(key, locale, value, updated_at) ` +
          `VALUES(${escapeSqlString(key)}, ${escapeSqlString(locale)}, ${escapeSqlString(value)}, unixepoch()) ` +
          `ON CONFLICT(key, locale) DO UPDATE SET value=excluded.value, updated_at=unixepoch();`,
      );
      count++;
    }
  }

  lines.push("COMMIT;");

  writeFileSync(OUT, lines.join("\n") + "\n", "utf8");

  console.log(`✓ Extracted ${Object.keys(translations).length} keys → ${count} translation rows`);
  console.log(`✓ Wrote SQL to ${OUT}`);
  console.log("");
  console.log("Apply locally:");
  console.log("  bunx wrangler d1 execute thg-cms --local --file=scripts/.tmp-migrate-i18n.sql");
  console.log("");
  console.log("Apply to production D1:");
  console.log("  bunx wrangler d1 execute thg-cms --remote --env production --file=scripts/.tmp-migrate-i18n.sql");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
