/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSalesPricingRouteRouteImport } from './routes/admin/sales/pricing/route'
import { Route as AdminContentServicesRouteRouteImport } from './routes/admin/content/services/route'
import { Route as AdminContentCareersRouteRouteImport } from './routes/admin/content/careers/route'
import { Route as AdminSystemUsersIndexRouteImport } from './routes/admin/system/users/index'
import { Route as AdminSystemTelegramIndexRouteImport } from './routes/admin/system/telegram/index'
import { Route as AdminSystemSettingsIndexRouteImport } from './routes/admin/system/settings/index'
import { Route as AdminSystemAuditIndexRouteImport } from './routes/admin/system/audit/index'
import { Route as AdminSalesTerminologyIndexRouteImport } from './routes/admin/sales/terminology/index'
import { Route as AdminSalesPricingIndexRouteImport } from './routes/admin/sales/pricing/index'
import { Route as AdminSalesLeadsIndexRouteImport } from './routes/admin/sales/leads/index'
import { Route as AdminContentTranslationsIndexRouteImport } from './routes/admin/content/translations/index'
import { Route as AdminContentTestimonialsIndexRouteImport } from './routes/admin/content/testimonials/index'
import { Route as AdminContentShippingRoutesIndexRouteImport } from './routes/admin/content/shipping-routes/index'
import { Route as AdminContentServicesIndexRouteImport } from './routes/admin/content/services/index'
import { Route as AdminContentServiceBlocksIndexRouteImport } from './routes/admin/content/service-blocks/index'
import { Route as AdminContentPoliciesIndexRouteImport } from './routes/admin/content/policies/index'
import { Route as AdminContentMediaIndexRouteImport } from './routes/admin/content/media/index'
import { Route as AdminContentMarketplacesIndexRouteImport } from './routes/admin/content/marketplaces/index'
import { Route as AdminContentLandingIndexRouteImport } from './routes/admin/content/landing/index'
import { Route as AdminContentGlossaryIndexRouteImport } from './routes/admin/content/glossary/index'
import { Route as AdminContentGalleryIndexRouteImport } from './routes/admin/content/gallery/index'
import { Route as AdminContentFaqsIndexRouteImport } from './routes/admin/content/faqs/index'
import { Route as AdminContentContactIndexRouteImport } from './routes/admin/content/contact/index'
import { Route as AdminContentCareersIndexRouteImport } from './routes/admin/content/careers/index'
import { Route as AdminContentBlogsIndexRouteImport } from './routes/admin/content/blogs/index'
import { Route as AdminAiSourcesIndexRouteImport } from './routes/admin/ai/sources/index'
import { Route as AdminAiReviewsIndexRouteImport } from './routes/admin/ai/reviews/index'
import { Route as AdminAiHistoryIndexRouteImport } from './routes/admin/ai/history/index'
import { Route as AdminAiChangeRequestsIndexRouteImport } from './routes/admin/ai/change-requests/index'
import { Route as AdminAiAgentJobsIndexRouteImport } from './routes/admin/ai/agent-jobs/index'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google/start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'
import { Route as AdminSalesPricingSlugRouteImport } from './routes/admin/sales/pricing/$slug'
import { Route as AdminContentShippingRoutesSlugRouteImport } from './routes/admin/content/shipping-routes/$slug'
import { Route as AdminContentServicesServiceIdRouteImport } from './routes/admin/content/services/$serviceId'
import { Route as AdminContentPoliciesSlugRouteImport } from './routes/admin/content/policies/$slug'
import { Route as AdminContentCareersApplicantsRouteImport } from './routes/admin/content/careers/applicants'
import { Route as AdminContentCareersJobIdRouteImport } from './routes/admin/content/careers/$jobId'
import { Route as AdminContentBlogsSlugRouteImport } from './routes/admin/content/blogs/$slug'
import { Route as ApiV1publicTranslationsIndexRouteImport } from './routes/api/v1/(public)/translations/index'
import { Route as ApiV1publicTestimonialsIndexRouteImport } from './routes/api/v1/(public)/testimonials/index'
import { Route as ApiV1publicSitemapIndexRouteImport } from './routes/api/v1/(public)/sitemap/index'
import { Route as ApiV1publicSiteSettingsIndexRouteImport } from './routes/api/v1/(public)/site-settings/index'
import { Route as ApiV1publicShippingRoutesIndexRouteImport } from './routes/api/v1/(public)/shipping-routes/index'
import { Route as ApiV1publicServicesIndexRouteImport } from './routes/api/v1/(public)/services/index'
import { Route as ApiV1publicServiceBlocksIndexRouteImport } from './routes/api/v1/(public)/service-blocks/index'
import { Route as ApiV1publicPricingIndexRouteImport } from './routes/api/v1/(public)/pricing/index'
import { Route as ApiV1publicPoliciesIndexRouteImport } from './routes/api/v1/(public)/policies/index'
import { Route as ApiV1publicOpenapiIndexRouteImport } from './routes/api/v1/(public)/openapi/index'
import { Route as ApiV1publicMarqueeImagesIndexRouteImport } from './routes/api/v1/(public)/marquee-images/index'
import { Route as ApiV1publicLeadsIndexRouteImport } from './routes/api/v1/(public)/leads/index'
import { Route as ApiV1publicJobsIndexRouteImport } from './routes/api/v1/(public)/jobs/index'
import { Route as ApiV1publicIntegrationsIndexRouteImport } from './routes/api/v1/(public)/integrations/index'
import { Route as ApiV1publicHomepageIndexRouteImport } from './routes/api/v1/(public)/homepage/index'
import { Route as ApiV1publicFaqsIndexRouteImport } from './routes/api/v1/(public)/faqs/index'
import { Route as ApiV1publicContactLocationsIndexRouteImport } from './routes/api/v1/(public)/contact-locations/index'
import { Route as ApiV1publicBlogIndexRouteImport } from './routes/api/v1/(public)/blog/index'
import { Route as ApiV1publicApplicantsIndexRouteImport } from './routes/api/v1/(public)/applicants/index'
import { Route as ApiV1publicApplicantCvIndexRouteImport } from './routes/api/v1/(public)/applicant-cv/index'
import { Route as ApiV1publicShippingRoutesSlugRouteImport } from './routes/api/v1/(public)/shipping-routes/$slug'
import { Route as ApiV1publicPricingSlugRouteImport } from './routes/api/v1/(public)/pricing/$slug'
import { Route as ApiV1publicPoliciesSlugRouteImport } from './routes/api/v1/(public)/policies/$slug'
import { Route as ApiV1publicMediaSplatRouteImport } from './routes/api/v1/(public)/media/$'
import { Route as ApiV1publicJobsSlugRouteImport } from './routes/api/v1/(public)/jobs/$slug'
import { Route as ApiV1publicBlogCategoriesRouteImport } from './routes/api/v1/(public)/blog/categories'
import { Route as ApiV1publicBlogSlugRouteImport } from './routes/api/v1/(public)/blog/$slug'
import { Route as ApiV1adminMediaUploadRouteImport } from './routes/api/v1/(admin)/media/upload'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesPricingRouteRoute = AdminSalesPricingRouteRouteImport.update({
  id: '/admin/sales/pricing',
  path: '/admin/sales/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentServicesRouteRoute =
  AdminContentServicesRouteRouteImport.update({
    id: '/admin/content/services',
    path: '/admin/content/services',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentCareersRouteRoute =
  AdminContentCareersRouteRouteImport.update({
    id: '/admin/content/careers',
    path: '/admin/content/careers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSystemUsersIndexRoute = AdminSystemUsersIndexRouteImport.update({
  id: '/admin/system/users/',
  path: '/admin/system/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemTelegramIndexRoute =
  AdminSystemTelegramIndexRouteImport.update({
    id: '/admin/system/telegram/',
    path: '/admin/system/telegram/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSystemSettingsIndexRoute =
  AdminSystemSettingsIndexRouteImport.update({
    id: '/admin/system/settings/',
    path: '/admin/system/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSystemAuditIndexRoute = AdminSystemAuditIndexRouteImport.update({
  id: '/admin/system/audit/',
  path: '/admin/system/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesTerminologyIndexRoute =
  AdminSalesTerminologyIndexRouteImport.update({
    id: '/admin/sales/terminology/',
    path: '/admin/sales/terminology/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSalesPricingIndexRoute = AdminSalesPricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSalesPricingRouteRoute,
} as any)
const AdminSalesLeadsIndexRoute = AdminSalesLeadsIndexRouteImport.update({
  id: '/admin/sales/leads/',
  path: '/admin/sales/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentTranslationsIndexRoute =
  AdminContentTranslationsIndexRouteImport.update({
    id: '/admin/content/translations/',
    path: '/admin/content/translations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentTestimonialsIndexRoute =
  AdminContentTestimonialsIndexRouteImport.update({
    id: '/admin/content/testimonials/',
    path: '/admin/content/testimonials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentShippingRoutesIndexRoute =
  AdminContentShippingRoutesIndexRouteImport.update({
    id: '/admin/content/shipping-routes/',
    path: '/admin/content/shipping-routes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentServicesIndexRoute =
  AdminContentServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentServicesRouteRoute,
  } as any)
const AdminContentServiceBlocksIndexRoute =
  AdminContentServiceBlocksIndexRouteImport.update({
    id: '/admin/content/service-blocks/',
    path: '/admin/content/service-blocks/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentPoliciesIndexRoute =
  AdminContentPoliciesIndexRouteImport.update({
    id: '/admin/content/policies/',
    path: '/admin/content/policies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentMediaIndexRoute = AdminContentMediaIndexRouteImport.update({
  id: '/admin/content/media/',
  path: '/admin/content/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentMarketplacesIndexRoute =
  AdminContentMarketplacesIndexRouteImport.update({
    id: '/admin/content/marketplaces/',
    path: '/admin/content/marketplaces/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentLandingIndexRoute =
  AdminContentLandingIndexRouteImport.update({
    id: '/admin/content/landing/',
    path: '/admin/content/landing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentGlossaryIndexRoute =
  AdminContentGlossaryIndexRouteImport.update({
    id: '/admin/content/glossary/',
    path: '/admin/content/glossary/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentGalleryIndexRoute =
  AdminContentGalleryIndexRouteImport.update({
    id: '/admin/content/gallery/',
    path: '/admin/content/gallery/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentFaqsIndexRoute = AdminContentFaqsIndexRouteImport.update({
  id: '/admin/content/faqs/',
  path: '/admin/content/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentContactIndexRoute =
  AdminContentContactIndexRouteImport.update({
    id: '/admin/content/contact/',
    path: '/admin/content/contact/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentCareersIndexRoute =
  AdminContentCareersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminContentCareersRouteRoute,
  } as any)
const AdminContentBlogsIndexRoute = AdminContentBlogsIndexRouteImport.update({
  id: '/admin/content/blogs/',
  path: '/admin/content/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiSourcesIndexRoute = AdminAiSourcesIndexRouteImport.update({
  id: '/admin/ai/sources/',
  path: '/admin/ai/sources/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiReviewsIndexRoute = AdminAiReviewsIndexRouteImport.update({
  id: '/admin/ai/reviews/',
  path: '/admin/ai/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiHistoryIndexRoute = AdminAiHistoryIndexRouteImport.update({
  id: '/admin/ai/history/',
  path: '/admin/ai/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiChangeRequestsIndexRoute =
  AdminAiChangeRequestsIndexRouteImport.update({
    id: '/admin/ai/change-requests/',
    path: '/admin/ai/change-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAiAgentJobsIndexRoute = AdminAiAgentJobsIndexRouteImport.update({
  id: '/admin/ai/agent-jobs/',
  path: '/admin/ai/agent-jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesPricingSlugRoute = AdminSalesPricingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminSalesPricingRouteRoute,
} as any)
const AdminContentShippingRoutesSlugRoute =
  AdminContentShippingRoutesSlugRouteImport.update({
    id: '/admin/content/shipping-routes/$slug',
    path: '/admin/content/shipping-routes/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentServicesServiceIdRoute =
  AdminContentServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AdminContentServicesRouteRoute,
  } as any)
const AdminContentPoliciesSlugRoute =
  AdminContentPoliciesSlugRouteImport.update({
    id: '/admin/content/policies/$slug',
    path: '/admin/content/policies/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContentCareersApplicantsRoute =
  AdminContentCareersApplicantsRouteImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => AdminContentCareersRouteRoute,
  } as any)
const AdminContentCareersJobIdRoute =
  AdminContentCareersJobIdRouteImport.update({
    id: '/$jobId',
    path: '/$jobId',
    getParentRoute: () => AdminContentCareersRouteRoute,
  } as any)
const AdminContentBlogsSlugRoute = AdminContentBlogsSlugRouteImport.update({
  id: '/admin/content/blogs/$slug',
  path: '/admin/content/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicTranslationsIndexRoute =
  ApiV1publicTranslationsIndexRouteImport.update({
    id: '/api/v1/(public)/translations/',
    path: '/api/v1/translations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicTestimonialsIndexRoute =
  ApiV1publicTestimonialsIndexRouteImport.update({
    id: '/api/v1/(public)/testimonials/',
    path: '/api/v1/testimonials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicSitemapIndexRoute = ApiV1publicSitemapIndexRouteImport.update({
  id: '/api/v1/(public)/sitemap/',
  path: '/api/v1/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicSiteSettingsIndexRoute =
  ApiV1publicSiteSettingsIndexRouteImport.update({
    id: '/api/v1/(public)/site-settings/',
    path: '/api/v1/site-settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicShippingRoutesIndexRoute =
  ApiV1publicShippingRoutesIndexRouteImport.update({
    id: '/api/v1/(public)/shipping-routes/',
    path: '/api/v1/shipping-routes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicServicesIndexRoute =
  ApiV1publicServicesIndexRouteImport.update({
    id: '/api/v1/(public)/services/',
    path: '/api/v1/services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicServiceBlocksIndexRoute =
  ApiV1publicServiceBlocksIndexRouteImport.update({
    id: '/api/v1/(public)/service-blocks/',
    path: '/api/v1/service-blocks/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicPricingIndexRoute = ApiV1publicPricingIndexRouteImport.update({
  id: '/api/v1/(public)/pricing/',
  path: '/api/v1/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicPoliciesIndexRoute =
  ApiV1publicPoliciesIndexRouteImport.update({
    id: '/api/v1/(public)/policies/',
    path: '/api/v1/policies/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicOpenapiIndexRoute = ApiV1publicOpenapiIndexRouteImport.update({
  id: '/api/v1/(public)/openapi/',
  path: '/api/v1/openapi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicMarqueeImagesIndexRoute =
  ApiV1publicMarqueeImagesIndexRouteImport.update({
    id: '/api/v1/(public)/marquee-images/',
    path: '/api/v1/marquee-images/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicLeadsIndexRoute = ApiV1publicLeadsIndexRouteImport.update({
  id: '/api/v1/(public)/leads/',
  path: '/api/v1/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicJobsIndexRoute = ApiV1publicJobsIndexRouteImport.update({
  id: '/api/v1/(public)/jobs/',
  path: '/api/v1/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicIntegrationsIndexRoute =
  ApiV1publicIntegrationsIndexRouteImport.update({
    id: '/api/v1/(public)/integrations/',
    path: '/api/v1/integrations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicHomepageIndexRoute =
  ApiV1publicHomepageIndexRouteImport.update({
    id: '/api/v1/(public)/homepage/',
    path: '/api/v1/homepage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicFaqsIndexRoute = ApiV1publicFaqsIndexRouteImport.update({
  id: '/api/v1/(public)/faqs/',
  path: '/api/v1/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicContactLocationsIndexRoute =
  ApiV1publicContactLocationsIndexRouteImport.update({
    id: '/api/v1/(public)/contact-locations/',
    path: '/api/v1/contact-locations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicBlogIndexRoute = ApiV1publicBlogIndexRouteImport.update({
  id: '/api/v1/(public)/blog/',
  path: '/api/v1/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicApplicantsIndexRoute =
  ApiV1publicApplicantsIndexRouteImport.update({
    id: '/api/v1/(public)/applicants/',
    path: '/api/v1/applicants/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicApplicantCvIndexRoute =
  ApiV1publicApplicantCvIndexRouteImport.update({
    id: '/api/v1/(public)/applicant-cv/',
    path: '/api/v1/applicant-cv/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicShippingRoutesSlugRoute =
  ApiV1publicShippingRoutesSlugRouteImport.update({
    id: '/api/v1/(public)/shipping-routes/$slug',
    path: '/api/v1/shipping-routes/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicPricingSlugRoute = ApiV1publicPricingSlugRouteImport.update({
  id: '/api/v1/(public)/pricing/$slug',
  path: '/api/v1/pricing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicPoliciesSlugRoute = ApiV1publicPoliciesSlugRouteImport.update({
  id: '/api/v1/(public)/policies/$slug',
  path: '/api/v1/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicMediaSplatRoute = ApiV1publicMediaSplatRouteImport.update({
  id: '/api/v1/(public)/media/$',
  path: '/api/v1/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicJobsSlugRoute = ApiV1publicJobsSlugRouteImport.update({
  id: '/api/v1/(public)/jobs/$slug',
  path: '/api/v1/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1publicBlogCategoriesRoute =
  ApiV1publicBlogCategoriesRouteImport.update({
    id: '/api/v1/(public)/blog/categories',
    path: '/api/v1/blog/categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1publicBlogSlugRoute = ApiV1publicBlogSlugRouteImport.update({
  id: '/api/v1/(public)/blog/$slug',
  path: '/api/v1/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1adminMediaUploadRoute = ApiV1adminMediaUploadRouteImport.update({
  id: '/api/v1/(admin)/media/upload',
  path: '/api/v1/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/careers': typeof AdminContentCareersRouteRouteWithChildren
  '/admin/content/services': typeof AdminContentServicesRouteRouteWithChildren
  '/admin/sales/pricing': typeof AdminSalesPricingRouteRouteWithChildren
  '/admin/content/blogs/$slug': typeof AdminContentBlogsSlugRoute
  '/admin/content/careers/$jobId': typeof AdminContentCareersJobIdRoute
  '/admin/content/careers/applicants': typeof AdminContentCareersApplicantsRoute
  '/admin/content/policies/$slug': typeof AdminContentPoliciesSlugRoute
  '/admin/content/services/$serviceId': typeof AdminContentServicesServiceIdRoute
  '/admin/content/shipping-routes/$slug': typeof AdminContentShippingRoutesSlugRoute
  '/admin/sales/pricing/$slug': typeof AdminSalesPricingSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/admin/ai/agent-jobs/': typeof AdminAiAgentJobsIndexRoute
  '/admin/ai/change-requests/': typeof AdminAiChangeRequestsIndexRoute
  '/admin/ai/history/': typeof AdminAiHistoryIndexRoute
  '/admin/ai/reviews/': typeof AdminAiReviewsIndexRoute
  '/admin/ai/sources/': typeof AdminAiSourcesIndexRoute
  '/admin/content/blogs/': typeof AdminContentBlogsIndexRoute
  '/admin/content/careers/': typeof AdminContentCareersIndexRoute
  '/admin/content/contact/': typeof AdminContentContactIndexRoute
  '/admin/content/faqs/': typeof AdminContentFaqsIndexRoute
  '/admin/content/gallery/': typeof AdminContentGalleryIndexRoute
  '/admin/content/glossary/': typeof AdminContentGlossaryIndexRoute
  '/admin/content/landing/': typeof AdminContentLandingIndexRoute
  '/admin/content/marketplaces/': typeof AdminContentMarketplacesIndexRoute
  '/admin/content/media/': typeof AdminContentMediaIndexRoute
  '/admin/content/policies/': typeof AdminContentPoliciesIndexRoute
  '/admin/content/service-blocks/': typeof AdminContentServiceBlocksIndexRoute
  '/admin/content/services/': typeof AdminContentServicesIndexRoute
  '/admin/content/shipping-routes/': typeof AdminContentShippingRoutesIndexRoute
  '/admin/content/testimonials/': typeof AdminContentTestimonialsIndexRoute
  '/admin/content/translations/': typeof AdminContentTranslationsIndexRoute
  '/admin/sales/leads/': typeof AdminSalesLeadsIndexRoute
  '/admin/sales/pricing/': typeof AdminSalesPricingIndexRoute
  '/admin/sales/terminology/': typeof AdminSalesTerminologyIndexRoute
  '/admin/system/audit/': typeof AdminSystemAuditIndexRoute
  '/admin/system/settings/': typeof AdminSystemSettingsIndexRoute
  '/admin/system/telegram/': typeof AdminSystemTelegramIndexRoute
  '/admin/system/users/': typeof AdminSystemUsersIndexRoute
  '/api/v1/media/upload': typeof ApiV1adminMediaUploadRoute
  '/api/v1/blog/$slug': typeof ApiV1publicBlogSlugRoute
  '/api/v1/blog/categories': typeof ApiV1publicBlogCategoriesRoute
  '/api/v1/jobs/$slug': typeof ApiV1publicJobsSlugRoute
  '/api/v1/media/$': typeof ApiV1publicMediaSplatRoute
  '/api/v1/policies/$slug': typeof ApiV1publicPoliciesSlugRoute
  '/api/v1/pricing/$slug': typeof ApiV1publicPricingSlugRoute
  '/api/v1/shipping-routes/$slug': typeof ApiV1publicShippingRoutesSlugRoute
  '/api/v1/applicant-cv/': typeof ApiV1publicApplicantCvIndexRoute
  '/api/v1/applicants/': typeof ApiV1publicApplicantsIndexRoute
  '/api/v1/blog/': typeof ApiV1publicBlogIndexRoute
  '/api/v1/contact-locations/': typeof ApiV1publicContactLocationsIndexRoute
  '/api/v1/faqs/': typeof ApiV1publicFaqsIndexRoute
  '/api/v1/homepage/': typeof ApiV1publicHomepageIndexRoute
  '/api/v1/integrations/': typeof ApiV1publicIntegrationsIndexRoute
  '/api/v1/jobs/': typeof ApiV1publicJobsIndexRoute
  '/api/v1/leads/': typeof ApiV1publicLeadsIndexRoute
  '/api/v1/marquee-images/': typeof ApiV1publicMarqueeImagesIndexRoute
  '/api/v1/openapi/': typeof ApiV1publicOpenapiIndexRoute
  '/api/v1/policies/': typeof ApiV1publicPoliciesIndexRoute
  '/api/v1/pricing/': typeof ApiV1publicPricingIndexRoute
  '/api/v1/service-blocks/': typeof ApiV1publicServiceBlocksIndexRoute
  '/api/v1/services/': typeof ApiV1publicServicesIndexRoute
  '/api/v1/shipping-routes/': typeof ApiV1publicShippingRoutesIndexRoute
  '/api/v1/site-settings/': typeof ApiV1publicSiteSettingsIndexRoute
  '/api/v1/sitemap/': typeof ApiV1publicSitemapIndexRoute
  '/api/v1/testimonials/': typeof ApiV1publicTestimonialsIndexRoute
  '/api/v1/translations/': typeof ApiV1publicTranslationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/content/blogs/$slug': typeof AdminContentBlogsSlugRoute
  '/admin/content/careers/$jobId': typeof AdminContentCareersJobIdRoute
  '/admin/content/careers/applicants': typeof AdminContentCareersApplicantsRoute
  '/admin/content/policies/$slug': typeof AdminContentPoliciesSlugRoute
  '/admin/content/services/$serviceId': typeof AdminContentServicesServiceIdRoute
  '/admin/content/shipping-routes/$slug': typeof AdminContentShippingRoutesSlugRoute
  '/admin/sales/pricing/$slug': typeof AdminSalesPricingSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/admin/ai/agent-jobs': typeof AdminAiAgentJobsIndexRoute
  '/admin/ai/change-requests': typeof AdminAiChangeRequestsIndexRoute
  '/admin/ai/history': typeof AdminAiHistoryIndexRoute
  '/admin/ai/reviews': typeof AdminAiReviewsIndexRoute
  '/admin/ai/sources': typeof AdminAiSourcesIndexRoute
  '/admin/content/blogs': typeof AdminContentBlogsIndexRoute
  '/admin/content/careers': typeof AdminContentCareersIndexRoute
  '/admin/content/contact': typeof AdminContentContactIndexRoute
  '/admin/content/faqs': typeof AdminContentFaqsIndexRoute
  '/admin/content/gallery': typeof AdminContentGalleryIndexRoute
  '/admin/content/glossary': typeof AdminContentGlossaryIndexRoute
  '/admin/content/landing': typeof AdminContentLandingIndexRoute
  '/admin/content/marketplaces': typeof AdminContentMarketplacesIndexRoute
  '/admin/content/media': typeof AdminContentMediaIndexRoute
  '/admin/content/policies': typeof AdminContentPoliciesIndexRoute
  '/admin/content/service-blocks': typeof AdminContentServiceBlocksIndexRoute
  '/admin/content/services': typeof AdminContentServicesIndexRoute
  '/admin/content/shipping-routes': typeof AdminContentShippingRoutesIndexRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsIndexRoute
  '/admin/content/translations': typeof AdminContentTranslationsIndexRoute
  '/admin/sales/leads': typeof AdminSalesLeadsIndexRoute
  '/admin/sales/pricing': typeof AdminSalesPricingIndexRoute
  '/admin/sales/terminology': typeof AdminSalesTerminologyIndexRoute
  '/admin/system/audit': typeof AdminSystemAuditIndexRoute
  '/admin/system/settings': typeof AdminSystemSettingsIndexRoute
  '/admin/system/telegram': typeof AdminSystemTelegramIndexRoute
  '/admin/system/users': typeof AdminSystemUsersIndexRoute
  '/api/v1/media/upload': typeof ApiV1adminMediaUploadRoute
  '/api/v1/blog/$slug': typeof ApiV1publicBlogSlugRoute
  '/api/v1/blog/categories': typeof ApiV1publicBlogCategoriesRoute
  '/api/v1/jobs/$slug': typeof ApiV1publicJobsSlugRoute
  '/api/v1/media/$': typeof ApiV1publicMediaSplatRoute
  '/api/v1/policies/$slug': typeof ApiV1publicPoliciesSlugRoute
  '/api/v1/pricing/$slug': typeof ApiV1publicPricingSlugRoute
  '/api/v1/shipping-routes/$slug': typeof ApiV1publicShippingRoutesSlugRoute
  '/api/v1/applicant-cv': typeof ApiV1publicApplicantCvIndexRoute
  '/api/v1/applicants': typeof ApiV1publicApplicantsIndexRoute
  '/api/v1/blog': typeof ApiV1publicBlogIndexRoute
  '/api/v1/contact-locations': typeof ApiV1publicContactLocationsIndexRoute
  '/api/v1/faqs': typeof ApiV1publicFaqsIndexRoute
  '/api/v1/homepage': typeof ApiV1publicHomepageIndexRoute
  '/api/v1/integrations': typeof ApiV1publicIntegrationsIndexRoute
  '/api/v1/jobs': typeof ApiV1publicJobsIndexRoute
  '/api/v1/leads': typeof ApiV1publicLeadsIndexRoute
  '/api/v1/marquee-images': typeof ApiV1publicMarqueeImagesIndexRoute
  '/api/v1/openapi': typeof ApiV1publicOpenapiIndexRoute
  '/api/v1/policies': typeof ApiV1publicPoliciesIndexRoute
  '/api/v1/pricing': typeof ApiV1publicPricingIndexRoute
  '/api/v1/service-blocks': typeof ApiV1publicServiceBlocksIndexRoute
  '/api/v1/services': typeof ApiV1publicServicesIndexRoute
  '/api/v1/shipping-routes': typeof ApiV1publicShippingRoutesIndexRoute
  '/api/v1/site-settings': typeof ApiV1publicSiteSettingsIndexRoute
  '/api/v1/sitemap': typeof ApiV1publicSitemapIndexRoute
  '/api/v1/testimonials': typeof ApiV1publicTestimonialsIndexRoute
  '/api/v1/translations': typeof ApiV1publicTranslationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/content/careers': typeof AdminContentCareersRouteRouteWithChildren
  '/admin/content/services': typeof AdminContentServicesRouteRouteWithChildren
  '/admin/sales/pricing': typeof AdminSalesPricingRouteRouteWithChildren
  '/admin/content/blogs/$slug': typeof AdminContentBlogsSlugRoute
  '/admin/content/careers/$jobId': typeof AdminContentCareersJobIdRoute
  '/admin/content/careers/applicants': typeof AdminContentCareersApplicantsRoute
  '/admin/content/policies/$slug': typeof AdminContentPoliciesSlugRoute
  '/admin/content/services/$serviceId': typeof AdminContentServicesServiceIdRoute
  '/admin/content/shipping-routes/$slug': typeof AdminContentShippingRoutesSlugRoute
  '/admin/sales/pricing/$slug': typeof AdminSalesPricingSlugRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/admin/ai/agent-jobs/': typeof AdminAiAgentJobsIndexRoute
  '/admin/ai/change-requests/': typeof AdminAiChangeRequestsIndexRoute
  '/admin/ai/history/': typeof AdminAiHistoryIndexRoute
  '/admin/ai/reviews/': typeof AdminAiReviewsIndexRoute
  '/admin/ai/sources/': typeof AdminAiSourcesIndexRoute
  '/admin/content/blogs/': typeof AdminContentBlogsIndexRoute
  '/admin/content/careers/': typeof AdminContentCareersIndexRoute
  '/admin/content/contact/': typeof AdminContentContactIndexRoute
  '/admin/content/faqs/': typeof AdminContentFaqsIndexRoute
  '/admin/content/gallery/': typeof AdminContentGalleryIndexRoute
  '/admin/content/glossary/': typeof AdminContentGlossaryIndexRoute
  '/admin/content/landing/': typeof AdminContentLandingIndexRoute
  '/admin/content/marketplaces/': typeof AdminContentMarketplacesIndexRoute
  '/admin/content/media/': typeof AdminContentMediaIndexRoute
  '/admin/content/policies/': typeof AdminContentPoliciesIndexRoute
  '/admin/content/service-blocks/': typeof AdminContentServiceBlocksIndexRoute
  '/admin/content/services/': typeof AdminContentServicesIndexRoute
  '/admin/content/shipping-routes/': typeof AdminContentShippingRoutesIndexRoute
  '/admin/content/testimonials/': typeof AdminContentTestimonialsIndexRoute
  '/admin/content/translations/': typeof AdminContentTranslationsIndexRoute
  '/admin/sales/leads/': typeof AdminSalesLeadsIndexRoute
  '/admin/sales/pricing/': typeof AdminSalesPricingIndexRoute
  '/admin/sales/terminology/': typeof AdminSalesTerminologyIndexRoute
  '/admin/system/audit/': typeof AdminSystemAuditIndexRoute
  '/admin/system/settings/': typeof AdminSystemSettingsIndexRoute
  '/admin/system/telegram/': typeof AdminSystemTelegramIndexRoute
  '/admin/system/users/': typeof AdminSystemUsersIndexRoute
  '/api/v1/(admin)/media/upload': typeof ApiV1adminMediaUploadRoute
  '/api/v1/(public)/blog/$slug': typeof ApiV1publicBlogSlugRoute
  '/api/v1/(public)/blog/categories': typeof ApiV1publicBlogCategoriesRoute
  '/api/v1/(public)/jobs/$slug': typeof ApiV1publicJobsSlugRoute
  '/api/v1/(public)/media/$': typeof ApiV1publicMediaSplatRoute
  '/api/v1/(public)/policies/$slug': typeof ApiV1publicPoliciesSlugRoute
  '/api/v1/(public)/pricing/$slug': typeof ApiV1publicPricingSlugRoute
  '/api/v1/(public)/shipping-routes/$slug': typeof ApiV1publicShippingRoutesSlugRoute
  '/api/v1/(public)/applicant-cv/': typeof ApiV1publicApplicantCvIndexRoute
  '/api/v1/(public)/applicants/': typeof ApiV1publicApplicantsIndexRoute
  '/api/v1/(public)/blog/': typeof ApiV1publicBlogIndexRoute
  '/api/v1/(public)/contact-locations/': typeof ApiV1publicContactLocationsIndexRoute
  '/api/v1/(public)/faqs/': typeof ApiV1publicFaqsIndexRoute
  '/api/v1/(public)/homepage/': typeof ApiV1publicHomepageIndexRoute
  '/api/v1/(public)/integrations/': typeof ApiV1publicIntegrationsIndexRoute
  '/api/v1/(public)/jobs/': typeof ApiV1publicJobsIndexRoute
  '/api/v1/(public)/leads/': typeof ApiV1publicLeadsIndexRoute
  '/api/v1/(public)/marquee-images/': typeof ApiV1publicMarqueeImagesIndexRoute
  '/api/v1/(public)/openapi/': typeof ApiV1publicOpenapiIndexRoute
  '/api/v1/(public)/policies/': typeof ApiV1publicPoliciesIndexRoute
  '/api/v1/(public)/pricing/': typeof ApiV1publicPricingIndexRoute
  '/api/v1/(public)/service-blocks/': typeof ApiV1publicServiceBlocksIndexRoute
  '/api/v1/(public)/services/': typeof ApiV1publicServicesIndexRoute
  '/api/v1/(public)/shipping-routes/': typeof ApiV1publicShippingRoutesIndexRoute
  '/api/v1/(public)/site-settings/': typeof ApiV1publicSiteSettingsIndexRoute
  '/api/v1/(public)/sitemap/': typeof ApiV1publicSitemapIndexRoute
  '/api/v1/(public)/testimonials/': typeof ApiV1publicTestimonialsIndexRoute
  '/api/v1/(public)/translations/': typeof ApiV1publicTranslationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/'
    | '/admin/content/careers'
    | '/admin/content/services'
    | '/admin/sales/pricing'
    | '/admin/content/blogs/$slug'
    | '/admin/content/careers/$jobId'
    | '/admin/content/careers/applicants'
    | '/admin/content/policies/$slug'
    | '/admin/content/services/$serviceId'
    | '/admin/content/shipping-routes/$slug'
    | '/admin/sales/pricing/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/admin/ai/agent-jobs/'
    | '/admin/ai/change-requests/'
    | '/admin/ai/history/'
    | '/admin/ai/reviews/'
    | '/admin/ai/sources/'
    | '/admin/content/blogs/'
    | '/admin/content/careers/'
    | '/admin/content/contact/'
    | '/admin/content/faqs/'
    | '/admin/content/gallery/'
    | '/admin/content/glossary/'
    | '/admin/content/landing/'
    | '/admin/content/marketplaces/'
    | '/admin/content/media/'
    | '/admin/content/policies/'
    | '/admin/content/service-blocks/'
    | '/admin/content/services/'
    | '/admin/content/shipping-routes/'
    | '/admin/content/testimonials/'
    | '/admin/content/translations/'
    | '/admin/sales/leads/'
    | '/admin/sales/pricing/'
    | '/admin/sales/terminology/'
    | '/admin/system/audit/'
    | '/admin/system/settings/'
    | '/admin/system/telegram/'
    | '/admin/system/users/'
    | '/api/v1/media/upload'
    | '/api/v1/blog/$slug'
    | '/api/v1/blog/categories'
    | '/api/v1/jobs/$slug'
    | '/api/v1/media/$'
    | '/api/v1/policies/$slug'
    | '/api/v1/pricing/$slug'
    | '/api/v1/shipping-routes/$slug'
    | '/api/v1/applicant-cv/'
    | '/api/v1/applicants/'
    | '/api/v1/blog/'
    | '/api/v1/contact-locations/'
    | '/api/v1/faqs/'
    | '/api/v1/homepage/'
    | '/api/v1/integrations/'
    | '/api/v1/jobs/'
    | '/api/v1/leads/'
    | '/api/v1/marquee-images/'
    | '/api/v1/openapi/'
    | '/api/v1/policies/'
    | '/api/v1/pricing/'
    | '/api/v1/service-blocks/'
    | '/api/v1/services/'
    | '/api/v1/shipping-routes/'
    | '/api/v1/site-settings/'
    | '/api/v1/sitemap/'
    | '/api/v1/testimonials/'
    | '/api/v1/translations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/content/blogs/$slug'
    | '/admin/content/careers/$jobId'
    | '/admin/content/careers/applicants'
    | '/admin/content/policies/$slug'
    | '/admin/content/services/$serviceId'
    | '/admin/content/shipping-routes/$slug'
    | '/admin/sales/pricing/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/admin/ai/agent-jobs'
    | '/admin/ai/change-requests'
    | '/admin/ai/history'
    | '/admin/ai/reviews'
    | '/admin/ai/sources'
    | '/admin/content/blogs'
    | '/admin/content/careers'
    | '/admin/content/contact'
    | '/admin/content/faqs'
    | '/admin/content/gallery'
    | '/admin/content/glossary'
    | '/admin/content/landing'
    | '/admin/content/marketplaces'
    | '/admin/content/media'
    | '/admin/content/policies'
    | '/admin/content/service-blocks'
    | '/admin/content/services'
    | '/admin/content/shipping-routes'
    | '/admin/content/testimonials'
    | '/admin/content/translations'
    | '/admin/sales/leads'
    | '/admin/sales/pricing'
    | '/admin/sales/terminology'
    | '/admin/system/audit'
    | '/admin/system/settings'
    | '/admin/system/telegram'
    | '/admin/system/users'
    | '/api/v1/media/upload'
    | '/api/v1/blog/$slug'
    | '/api/v1/blog/categories'
    | '/api/v1/jobs/$slug'
    | '/api/v1/media/$'
    | '/api/v1/policies/$slug'
    | '/api/v1/pricing/$slug'
    | '/api/v1/shipping-routes/$slug'
    | '/api/v1/applicant-cv'
    | '/api/v1/applicants'
    | '/api/v1/blog'
    | '/api/v1/contact-locations'
    | '/api/v1/faqs'
    | '/api/v1/homepage'
    | '/api/v1/integrations'
    | '/api/v1/jobs'
    | '/api/v1/leads'
    | '/api/v1/marquee-images'
    | '/api/v1/openapi'
    | '/api/v1/policies'
    | '/api/v1/pricing'
    | '/api/v1/service-blocks'
    | '/api/v1/services'
    | '/api/v1/shipping-routes'
    | '/api/v1/site-settings'
    | '/api/v1/sitemap'
    | '/api/v1/testimonials'
    | '/api/v1/translations'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/'
    | '/admin/content/careers'
    | '/admin/content/services'
    | '/admin/sales/pricing'
    | '/admin/content/blogs/$slug'
    | '/admin/content/careers/$jobId'
    | '/admin/content/careers/applicants'
    | '/admin/content/policies/$slug'
    | '/admin/content/services/$serviceId'
    | '/admin/content/shipping-routes/$slug'
    | '/admin/sales/pricing/$slug'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/admin/ai/agent-jobs/'
    | '/admin/ai/change-requests/'
    | '/admin/ai/history/'
    | '/admin/ai/reviews/'
    | '/admin/ai/sources/'
    | '/admin/content/blogs/'
    | '/admin/content/careers/'
    | '/admin/content/contact/'
    | '/admin/content/faqs/'
    | '/admin/content/gallery/'
    | '/admin/content/glossary/'
    | '/admin/content/landing/'
    | '/admin/content/marketplaces/'
    | '/admin/content/media/'
    | '/admin/content/policies/'
    | '/admin/content/service-blocks/'
    | '/admin/content/services/'
    | '/admin/content/shipping-routes/'
    | '/admin/content/testimonials/'
    | '/admin/content/translations/'
    | '/admin/sales/leads/'
    | '/admin/sales/pricing/'
    | '/admin/sales/terminology/'
    | '/admin/system/audit/'
    | '/admin/system/settings/'
    | '/admin/system/telegram/'
    | '/admin/system/users/'
    | '/api/v1/(admin)/media/upload'
    | '/api/v1/(public)/blog/$slug'
    | '/api/v1/(public)/blog/categories'
    | '/api/v1/(public)/jobs/$slug'
    | '/api/v1/(public)/media/$'
    | '/api/v1/(public)/policies/$slug'
    | '/api/v1/(public)/pricing/$slug'
    | '/api/v1/(public)/shipping-routes/$slug'
    | '/api/v1/(public)/applicant-cv/'
    | '/api/v1/(public)/applicants/'
    | '/api/v1/(public)/blog/'
    | '/api/v1/(public)/contact-locations/'
    | '/api/v1/(public)/faqs/'
    | '/api/v1/(public)/homepage/'
    | '/api/v1/(public)/integrations/'
    | '/api/v1/(public)/jobs/'
    | '/api/v1/(public)/leads/'
    | '/api/v1/(public)/marquee-images/'
    | '/api/v1/(public)/openapi/'
    | '/api/v1/(public)/policies/'
    | '/api/v1/(public)/pricing/'
    | '/api/v1/(public)/service-blocks/'
    | '/api/v1/(public)/services/'
    | '/api/v1/(public)/shipping-routes/'
    | '/api/v1/(public)/site-settings/'
    | '/api/v1/(public)/sitemap/'
    | '/api/v1/(public)/testimonials/'
    | '/api/v1/(public)/translations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContentCareersRouteRoute: typeof AdminContentCareersRouteRouteWithChildren
  AdminContentServicesRouteRoute: typeof AdminContentServicesRouteRouteWithChildren
  AdminSalesPricingRouteRoute: typeof AdminSalesPricingRouteRouteWithChildren
  AdminContentBlogsSlugRoute: typeof AdminContentBlogsSlugRoute
  AdminContentPoliciesSlugRoute: typeof AdminContentPoliciesSlugRoute
  AdminContentShippingRoutesSlugRoute: typeof AdminContentShippingRoutesSlugRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  AdminAiAgentJobsIndexRoute: typeof AdminAiAgentJobsIndexRoute
  AdminAiChangeRequestsIndexRoute: typeof AdminAiChangeRequestsIndexRoute
  AdminAiHistoryIndexRoute: typeof AdminAiHistoryIndexRoute
  AdminAiReviewsIndexRoute: typeof AdminAiReviewsIndexRoute
  AdminAiSourcesIndexRoute: typeof AdminAiSourcesIndexRoute
  AdminContentBlogsIndexRoute: typeof AdminContentBlogsIndexRoute
  AdminContentContactIndexRoute: typeof AdminContentContactIndexRoute
  AdminContentFaqsIndexRoute: typeof AdminContentFaqsIndexRoute
  AdminContentGalleryIndexRoute: typeof AdminContentGalleryIndexRoute
  AdminContentGlossaryIndexRoute: typeof AdminContentGlossaryIndexRoute
  AdminContentLandingIndexRoute: typeof AdminContentLandingIndexRoute
  AdminContentMarketplacesIndexRoute: typeof AdminContentMarketplacesIndexRoute
  AdminContentMediaIndexRoute: typeof AdminContentMediaIndexRoute
  AdminContentPoliciesIndexRoute: typeof AdminContentPoliciesIndexRoute
  AdminContentServiceBlocksIndexRoute: typeof AdminContentServiceBlocksIndexRoute
  AdminContentShippingRoutesIndexRoute: typeof AdminContentShippingRoutesIndexRoute
  AdminContentTestimonialsIndexRoute: typeof AdminContentTestimonialsIndexRoute
  AdminContentTranslationsIndexRoute: typeof AdminContentTranslationsIndexRoute
  AdminSalesLeadsIndexRoute: typeof AdminSalesLeadsIndexRoute
  AdminSalesTerminologyIndexRoute: typeof AdminSalesTerminologyIndexRoute
  AdminSystemAuditIndexRoute: typeof AdminSystemAuditIndexRoute
  AdminSystemSettingsIndexRoute: typeof AdminSystemSettingsIndexRoute
  AdminSystemTelegramIndexRoute: typeof AdminSystemTelegramIndexRoute
  AdminSystemUsersIndexRoute: typeof AdminSystemUsersIndexRoute
  ApiV1adminMediaUploadRoute: typeof ApiV1adminMediaUploadRoute
  ApiV1publicBlogSlugRoute: typeof ApiV1publicBlogSlugRoute
  ApiV1publicBlogCategoriesRoute: typeof ApiV1publicBlogCategoriesRoute
  ApiV1publicJobsSlugRoute: typeof ApiV1publicJobsSlugRoute
  ApiV1publicMediaSplatRoute: typeof ApiV1publicMediaSplatRoute
  ApiV1publicPoliciesSlugRoute: typeof ApiV1publicPoliciesSlugRoute
  ApiV1publicPricingSlugRoute: typeof ApiV1publicPricingSlugRoute
  ApiV1publicShippingRoutesSlugRoute: typeof ApiV1publicShippingRoutesSlugRoute
  ApiV1publicApplicantCvIndexRoute: typeof ApiV1publicApplicantCvIndexRoute
  ApiV1publicApplicantsIndexRoute: typeof ApiV1publicApplicantsIndexRoute
  ApiV1publicBlogIndexRoute: typeof ApiV1publicBlogIndexRoute
  ApiV1publicContactLocationsIndexRoute: typeof ApiV1publicContactLocationsIndexRoute
  ApiV1publicFaqsIndexRoute: typeof ApiV1publicFaqsIndexRoute
  ApiV1publicHomepageIndexRoute: typeof ApiV1publicHomepageIndexRoute
  ApiV1publicIntegrationsIndexRoute: typeof ApiV1publicIntegrationsIndexRoute
  ApiV1publicJobsIndexRoute: typeof ApiV1publicJobsIndexRoute
  ApiV1publicLeadsIndexRoute: typeof ApiV1publicLeadsIndexRoute
  ApiV1publicMarqueeImagesIndexRoute: typeof ApiV1publicMarqueeImagesIndexRoute
  ApiV1publicOpenapiIndexRoute: typeof ApiV1publicOpenapiIndexRoute
  ApiV1publicPoliciesIndexRoute: typeof ApiV1publicPoliciesIndexRoute
  ApiV1publicPricingIndexRoute: typeof ApiV1publicPricingIndexRoute
  ApiV1publicServiceBlocksIndexRoute: typeof ApiV1publicServiceBlocksIndexRoute
  ApiV1publicServicesIndexRoute: typeof ApiV1publicServicesIndexRoute
  ApiV1publicShippingRoutesIndexRoute: typeof ApiV1publicShippingRoutesIndexRoute
  ApiV1publicSiteSettingsIndexRoute: typeof ApiV1publicSiteSettingsIndexRoute
  ApiV1publicSitemapIndexRoute: typeof ApiV1publicSitemapIndexRoute
  ApiV1publicTestimonialsIndexRoute: typeof ApiV1publicTestimonialsIndexRoute
  ApiV1publicTranslationsIndexRoute: typeof ApiV1publicTranslationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales/pricing': {
      id: '/admin/sales/pricing'
      path: '/admin/sales/pricing'
      fullPath: '/admin/sales/pricing'
      preLoaderRoute: typeof AdminSalesPricingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/services': {
      id: '/admin/content/services'
      path: '/admin/content/services'
      fullPath: '/admin/content/services'
      preLoaderRoute: typeof AdminContentServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/careers': {
      id: '/admin/content/careers'
      path: '/admin/content/careers'
      fullPath: '/admin/content/careers'
      preLoaderRoute: typeof AdminContentCareersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/users/': {
      id: '/admin/system/users/'
      path: '/admin/system/users'
      fullPath: '/admin/system/users/'
      preLoaderRoute: typeof AdminSystemUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/telegram/': {
      id: '/admin/system/telegram/'
      path: '/admin/system/telegram'
      fullPath: '/admin/system/telegram/'
      preLoaderRoute: typeof AdminSystemTelegramIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/settings/': {
      id: '/admin/system/settings/'
      path: '/admin/system/settings'
      fullPath: '/admin/system/settings/'
      preLoaderRoute: typeof AdminSystemSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/audit/': {
      id: '/admin/system/audit/'
      path: '/admin/system/audit'
      fullPath: '/admin/system/audit/'
      preLoaderRoute: typeof AdminSystemAuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales/terminology/': {
      id: '/admin/sales/terminology/'
      path: '/admin/sales/terminology'
      fullPath: '/admin/sales/terminology/'
      preLoaderRoute: typeof AdminSalesTerminologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales/pricing/': {
      id: '/admin/sales/pricing/'
      path: '/'
      fullPath: '/admin/sales/pricing/'
      preLoaderRoute: typeof AdminSalesPricingIndexRouteImport
      parentRoute: typeof AdminSalesPricingRouteRoute
    }
    '/admin/sales/leads/': {
      id: '/admin/sales/leads/'
      path: '/admin/sales/leads'
      fullPath: '/admin/sales/leads/'
      preLoaderRoute: typeof AdminSalesLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/translations/': {
      id: '/admin/content/translations/'
      path: '/admin/content/translations'
      fullPath: '/admin/content/translations/'
      preLoaderRoute: typeof AdminContentTranslationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/testimonials/': {
      id: '/admin/content/testimonials/'
      path: '/admin/content/testimonials'
      fullPath: '/admin/content/testimonials/'
      preLoaderRoute: typeof AdminContentTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/shipping-routes/': {
      id: '/admin/content/shipping-routes/'
      path: '/admin/content/shipping-routes'
      fullPath: '/admin/content/shipping-routes/'
      preLoaderRoute: typeof AdminContentShippingRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/services/': {
      id: '/admin/content/services/'
      path: '/'
      fullPath: '/admin/content/services/'
      preLoaderRoute: typeof AdminContentServicesIndexRouteImport
      parentRoute: typeof AdminContentServicesRouteRoute
    }
    '/admin/content/service-blocks/': {
      id: '/admin/content/service-blocks/'
      path: '/admin/content/service-blocks'
      fullPath: '/admin/content/service-blocks/'
      preLoaderRoute: typeof AdminContentServiceBlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/policies/': {
      id: '/admin/content/policies/'
      path: '/admin/content/policies'
      fullPath: '/admin/content/policies/'
      preLoaderRoute: typeof AdminContentPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/media/': {
      id: '/admin/content/media/'
      path: '/admin/content/media'
      fullPath: '/admin/content/media/'
      preLoaderRoute: typeof AdminContentMediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/marketplaces/': {
      id: '/admin/content/marketplaces/'
      path: '/admin/content/marketplaces'
      fullPath: '/admin/content/marketplaces/'
      preLoaderRoute: typeof AdminContentMarketplacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/landing/': {
      id: '/admin/content/landing/'
      path: '/admin/content/landing'
      fullPath: '/admin/content/landing/'
      preLoaderRoute: typeof AdminContentLandingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/glossary/': {
      id: '/admin/content/glossary/'
      path: '/admin/content/glossary'
      fullPath: '/admin/content/glossary/'
      preLoaderRoute: typeof AdminContentGlossaryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/gallery/': {
      id: '/admin/content/gallery/'
      path: '/admin/content/gallery'
      fullPath: '/admin/content/gallery/'
      preLoaderRoute: typeof AdminContentGalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/faqs/': {
      id: '/admin/content/faqs/'
      path: '/admin/content/faqs'
      fullPath: '/admin/content/faqs/'
      preLoaderRoute: typeof AdminContentFaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/contact/': {
      id: '/admin/content/contact/'
      path: '/admin/content/contact'
      fullPath: '/admin/content/contact/'
      preLoaderRoute: typeof AdminContentContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/careers/': {
      id: '/admin/content/careers/'
      path: '/'
      fullPath: '/admin/content/careers/'
      preLoaderRoute: typeof AdminContentCareersIndexRouteImport
      parentRoute: typeof AdminContentCareersRouteRoute
    }
    '/admin/content/blogs/': {
      id: '/admin/content/blogs/'
      path: '/admin/content/blogs'
      fullPath: '/admin/content/blogs/'
      preLoaderRoute: typeof AdminContentBlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/sources/': {
      id: '/admin/ai/sources/'
      path: '/admin/ai/sources'
      fullPath: '/admin/ai/sources/'
      preLoaderRoute: typeof AdminAiSourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/reviews/': {
      id: '/admin/ai/reviews/'
      path: '/admin/ai/reviews'
      fullPath: '/admin/ai/reviews/'
      preLoaderRoute: typeof AdminAiReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/history/': {
      id: '/admin/ai/history/'
      path: '/admin/ai/history'
      fullPath: '/admin/ai/history/'
      preLoaderRoute: typeof AdminAiHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/change-requests/': {
      id: '/admin/ai/change-requests/'
      path: '/admin/ai/change-requests'
      fullPath: '/admin/ai/change-requests/'
      preLoaderRoute: typeof AdminAiChangeRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai/agent-jobs/': {
      id: '/admin/ai/agent-jobs/'
      path: '/admin/ai/agent-jobs'
      fullPath: '/admin/ai/agent-jobs/'
      preLoaderRoute: typeof AdminAiAgentJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales/pricing/$slug': {
      id: '/admin/sales/pricing/$slug'
      path: '/$slug'
      fullPath: '/admin/sales/pricing/$slug'
      preLoaderRoute: typeof AdminSalesPricingSlugRouteImport
      parentRoute: typeof AdminSalesPricingRouteRoute
    }
    '/admin/content/shipping-routes/$slug': {
      id: '/admin/content/shipping-routes/$slug'
      path: '/admin/content/shipping-routes/$slug'
      fullPath: '/admin/content/shipping-routes/$slug'
      preLoaderRoute: typeof AdminContentShippingRoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/services/$serviceId': {
      id: '/admin/content/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/admin/content/services/$serviceId'
      preLoaderRoute: typeof AdminContentServicesServiceIdRouteImport
      parentRoute: typeof AdminContentServicesRouteRoute
    }
    '/admin/content/policies/$slug': {
      id: '/admin/content/policies/$slug'
      path: '/admin/content/policies/$slug'
      fullPath: '/admin/content/policies/$slug'
      preLoaderRoute: typeof AdminContentPoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/careers/applicants': {
      id: '/admin/content/careers/applicants'
      path: '/applicants'
      fullPath: '/admin/content/careers/applicants'
      preLoaderRoute: typeof AdminContentCareersApplicantsRouteImport
      parentRoute: typeof AdminContentCareersRouteRoute
    }
    '/admin/content/careers/$jobId': {
      id: '/admin/content/careers/$jobId'
      path: '/$jobId'
      fullPath: '/admin/content/careers/$jobId'
      preLoaderRoute: typeof AdminContentCareersJobIdRouteImport
      parentRoute: typeof AdminContentCareersRouteRoute
    }
    '/admin/content/blogs/$slug': {
      id: '/admin/content/blogs/$slug'
      path: '/admin/content/blogs/$slug'
      fullPath: '/admin/content/blogs/$slug'
      preLoaderRoute: typeof AdminContentBlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/translations/': {
      id: '/api/v1/(public)/translations/'
      path: '/api/v1/translations'
      fullPath: '/api/v1/translations/'
      preLoaderRoute: typeof ApiV1publicTranslationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/testimonials/': {
      id: '/api/v1/(public)/testimonials/'
      path: '/api/v1/testimonials'
      fullPath: '/api/v1/testimonials/'
      preLoaderRoute: typeof ApiV1publicTestimonialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/sitemap/': {
      id: '/api/v1/(public)/sitemap/'
      path: '/api/v1/sitemap'
      fullPath: '/api/v1/sitemap/'
      preLoaderRoute: typeof ApiV1publicSitemapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/site-settings/': {
      id: '/api/v1/(public)/site-settings/'
      path: '/api/v1/site-settings'
      fullPath: '/api/v1/site-settings/'
      preLoaderRoute: typeof ApiV1publicSiteSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/shipping-routes/': {
      id: '/api/v1/(public)/shipping-routes/'
      path: '/api/v1/shipping-routes'
      fullPath: '/api/v1/shipping-routes/'
      preLoaderRoute: typeof ApiV1publicShippingRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/services/': {
      id: '/api/v1/(public)/services/'
      path: '/api/v1/services'
      fullPath: '/api/v1/services/'
      preLoaderRoute: typeof ApiV1publicServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/service-blocks/': {
      id: '/api/v1/(public)/service-blocks/'
      path: '/api/v1/service-blocks'
      fullPath: '/api/v1/service-blocks/'
      preLoaderRoute: typeof ApiV1publicServiceBlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/pricing/': {
      id: '/api/v1/(public)/pricing/'
      path: '/api/v1/pricing'
      fullPath: '/api/v1/pricing/'
      preLoaderRoute: typeof ApiV1publicPricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/policies/': {
      id: '/api/v1/(public)/policies/'
      path: '/api/v1/policies'
      fullPath: '/api/v1/policies/'
      preLoaderRoute: typeof ApiV1publicPoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/openapi/': {
      id: '/api/v1/(public)/openapi/'
      path: '/api/v1/openapi'
      fullPath: '/api/v1/openapi/'
      preLoaderRoute: typeof ApiV1publicOpenapiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/marquee-images/': {
      id: '/api/v1/(public)/marquee-images/'
      path: '/api/v1/marquee-images'
      fullPath: '/api/v1/marquee-images/'
      preLoaderRoute: typeof ApiV1publicMarqueeImagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/leads/': {
      id: '/api/v1/(public)/leads/'
      path: '/api/v1/leads'
      fullPath: '/api/v1/leads/'
      preLoaderRoute: typeof ApiV1publicLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/jobs/': {
      id: '/api/v1/(public)/jobs/'
      path: '/api/v1/jobs'
      fullPath: '/api/v1/jobs/'
      preLoaderRoute: typeof ApiV1publicJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/integrations/': {
      id: '/api/v1/(public)/integrations/'
      path: '/api/v1/integrations'
      fullPath: '/api/v1/integrations/'
      preLoaderRoute: typeof ApiV1publicIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/homepage/': {
      id: '/api/v1/(public)/homepage/'
      path: '/api/v1/homepage'
      fullPath: '/api/v1/homepage/'
      preLoaderRoute: typeof ApiV1publicHomepageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/faqs/': {
      id: '/api/v1/(public)/faqs/'
      path: '/api/v1/faqs'
      fullPath: '/api/v1/faqs/'
      preLoaderRoute: typeof ApiV1publicFaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/contact-locations/': {
      id: '/api/v1/(public)/contact-locations/'
      path: '/api/v1/contact-locations'
      fullPath: '/api/v1/contact-locations/'
      preLoaderRoute: typeof ApiV1publicContactLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/blog/': {
      id: '/api/v1/(public)/blog/'
      path: '/api/v1/blog'
      fullPath: '/api/v1/blog/'
      preLoaderRoute: typeof ApiV1publicBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/applicants/': {
      id: '/api/v1/(public)/applicants/'
      path: '/api/v1/applicants'
      fullPath: '/api/v1/applicants/'
      preLoaderRoute: typeof ApiV1publicApplicantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/applicant-cv/': {
      id: '/api/v1/(public)/applicant-cv/'
      path: '/api/v1/applicant-cv'
      fullPath: '/api/v1/applicant-cv/'
      preLoaderRoute: typeof ApiV1publicApplicantCvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/shipping-routes/$slug': {
      id: '/api/v1/(public)/shipping-routes/$slug'
      path: '/api/v1/shipping-routes/$slug'
      fullPath: '/api/v1/shipping-routes/$slug'
      preLoaderRoute: typeof ApiV1publicShippingRoutesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/pricing/$slug': {
      id: '/api/v1/(public)/pricing/$slug'
      path: '/api/v1/pricing/$slug'
      fullPath: '/api/v1/pricing/$slug'
      preLoaderRoute: typeof ApiV1publicPricingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/policies/$slug': {
      id: '/api/v1/(public)/policies/$slug'
      path: '/api/v1/policies/$slug'
      fullPath: '/api/v1/policies/$slug'
      preLoaderRoute: typeof ApiV1publicPoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/media/$': {
      id: '/api/v1/(public)/media/$'
      path: '/api/v1/media/$'
      fullPath: '/api/v1/media/$'
      preLoaderRoute: typeof ApiV1publicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/jobs/$slug': {
      id: '/api/v1/(public)/jobs/$slug'
      path: '/api/v1/jobs/$slug'
      fullPath: '/api/v1/jobs/$slug'
      preLoaderRoute: typeof ApiV1publicJobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/blog/categories': {
      id: '/api/v1/(public)/blog/categories'
      path: '/api/v1/blog/categories'
      fullPath: '/api/v1/blog/categories'
      preLoaderRoute: typeof ApiV1publicBlogCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(public)/blog/$slug': {
      id: '/api/v1/(public)/blog/$slug'
      path: '/api/v1/blog/$slug'
      fullPath: '/api/v1/blog/$slug'
      preLoaderRoute: typeof ApiV1publicBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/(admin)/media/upload': {
      id: '/api/v1/(admin)/media/upload'
      path: '/api/v1/media/upload'
      fullPath: '/api/v1/media/upload'
      preLoaderRoute: typeof ApiV1adminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminContentCareersRouteRouteChildren {
  AdminContentCareersJobIdRoute: typeof AdminContentCareersJobIdRoute
  AdminContentCareersApplicantsRoute: typeof AdminContentCareersApplicantsRoute
  AdminContentCareersIndexRoute: typeof AdminContentCareersIndexRoute
}

const AdminContentCareersRouteRouteChildren: AdminContentCareersRouteRouteChildren =
  {
    AdminContentCareersJobIdRoute: AdminContentCareersJobIdRoute,
    AdminContentCareersApplicantsRoute: AdminContentCareersApplicantsRoute,
    AdminContentCareersIndexRoute: AdminContentCareersIndexRoute,
  }

const AdminContentCareersRouteRouteWithChildren =
  AdminContentCareersRouteRoute._addFileChildren(
    AdminContentCareersRouteRouteChildren,
  )

interface AdminContentServicesRouteRouteChildren {
  AdminContentServicesServiceIdRoute: typeof AdminContentServicesServiceIdRoute
  AdminContentServicesIndexRoute: typeof AdminContentServicesIndexRoute
}

const AdminContentServicesRouteRouteChildren: AdminContentServicesRouteRouteChildren =
  {
    AdminContentServicesServiceIdRoute: AdminContentServicesServiceIdRoute,
    AdminContentServicesIndexRoute: AdminContentServicesIndexRoute,
  }

const AdminContentServicesRouteRouteWithChildren =
  AdminContentServicesRouteRoute._addFileChildren(
    AdminContentServicesRouteRouteChildren,
  )

interface AdminSalesPricingRouteRouteChildren {
  AdminSalesPricingSlugRoute: typeof AdminSalesPricingSlugRoute
  AdminSalesPricingIndexRoute: typeof AdminSalesPricingIndexRoute
}

const AdminSalesPricingRouteRouteChildren: AdminSalesPricingRouteRouteChildren =
  {
    AdminSalesPricingSlugRoute: AdminSalesPricingSlugRoute,
    AdminSalesPricingIndexRoute: AdminSalesPricingIndexRoute,
  }

const AdminSalesPricingRouteRouteWithChildren =
  AdminSalesPricingRouteRoute._addFileChildren(
    AdminSalesPricingRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContentCareersRouteRoute: AdminContentCareersRouteRouteWithChildren,
  AdminContentServicesRouteRoute: AdminContentServicesRouteRouteWithChildren,
  AdminSalesPricingRouteRoute: AdminSalesPricingRouteRouteWithChildren,
  AdminContentBlogsSlugRoute: AdminContentBlogsSlugRoute,
  AdminContentPoliciesSlugRoute: AdminContentPoliciesSlugRoute,
  AdminContentShippingRoutesSlugRoute: AdminContentShippingRoutesSlugRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  AdminAiAgentJobsIndexRoute: AdminAiAgentJobsIndexRoute,
  AdminAiChangeRequestsIndexRoute: AdminAiChangeRequestsIndexRoute,
  AdminAiHistoryIndexRoute: AdminAiHistoryIndexRoute,
  AdminAiReviewsIndexRoute: AdminAiReviewsIndexRoute,
  AdminAiSourcesIndexRoute: AdminAiSourcesIndexRoute,
  AdminContentBlogsIndexRoute: AdminContentBlogsIndexRoute,
  AdminContentContactIndexRoute: AdminContentContactIndexRoute,
  AdminContentFaqsIndexRoute: AdminContentFaqsIndexRoute,
  AdminContentGalleryIndexRoute: AdminContentGalleryIndexRoute,
  AdminContentGlossaryIndexRoute: AdminContentGlossaryIndexRoute,
  AdminContentLandingIndexRoute: AdminContentLandingIndexRoute,
  AdminContentMarketplacesIndexRoute: AdminContentMarketplacesIndexRoute,
  AdminContentMediaIndexRoute: AdminContentMediaIndexRoute,
  AdminContentPoliciesIndexRoute: AdminContentPoliciesIndexRoute,
  AdminContentServiceBlocksIndexRoute: AdminContentServiceBlocksIndexRoute,
  AdminContentShippingRoutesIndexRoute: AdminContentShippingRoutesIndexRoute,
  AdminContentTestimonialsIndexRoute: AdminContentTestimonialsIndexRoute,
  AdminContentTranslationsIndexRoute: AdminContentTranslationsIndexRoute,
  AdminSalesLeadsIndexRoute: AdminSalesLeadsIndexRoute,
  AdminSalesTerminologyIndexRoute: AdminSalesTerminologyIndexRoute,
  AdminSystemAuditIndexRoute: AdminSystemAuditIndexRoute,
  AdminSystemSettingsIndexRoute: AdminSystemSettingsIndexRoute,
  AdminSystemTelegramIndexRoute: AdminSystemTelegramIndexRoute,
  AdminSystemUsersIndexRoute: AdminSystemUsersIndexRoute,
  ApiV1adminMediaUploadRoute: ApiV1adminMediaUploadRoute,
  ApiV1publicBlogSlugRoute: ApiV1publicBlogSlugRoute,
  ApiV1publicBlogCategoriesRoute: ApiV1publicBlogCategoriesRoute,
  ApiV1publicJobsSlugRoute: ApiV1publicJobsSlugRoute,
  ApiV1publicMediaSplatRoute: ApiV1publicMediaSplatRoute,
  ApiV1publicPoliciesSlugRoute: ApiV1publicPoliciesSlugRoute,
  ApiV1publicPricingSlugRoute: ApiV1publicPricingSlugRoute,
  ApiV1publicShippingRoutesSlugRoute: ApiV1publicShippingRoutesSlugRoute,
  ApiV1publicApplicantCvIndexRoute: ApiV1publicApplicantCvIndexRoute,
  ApiV1publicApplicantsIndexRoute: ApiV1publicApplicantsIndexRoute,
  ApiV1publicBlogIndexRoute: ApiV1publicBlogIndexRoute,
  ApiV1publicContactLocationsIndexRoute: ApiV1publicContactLocationsIndexRoute,
  ApiV1publicFaqsIndexRoute: ApiV1publicFaqsIndexRoute,
  ApiV1publicHomepageIndexRoute: ApiV1publicHomepageIndexRoute,
  ApiV1publicIntegrationsIndexRoute: ApiV1publicIntegrationsIndexRoute,
  ApiV1publicJobsIndexRoute: ApiV1publicJobsIndexRoute,
  ApiV1publicLeadsIndexRoute: ApiV1publicLeadsIndexRoute,
  ApiV1publicMarqueeImagesIndexRoute: ApiV1publicMarqueeImagesIndexRoute,
  ApiV1publicOpenapiIndexRoute: ApiV1publicOpenapiIndexRoute,
  ApiV1publicPoliciesIndexRoute: ApiV1publicPoliciesIndexRoute,
  ApiV1publicPricingIndexRoute: ApiV1publicPricingIndexRoute,
  ApiV1publicServiceBlocksIndexRoute: ApiV1publicServiceBlocksIndexRoute,
  ApiV1publicServicesIndexRoute: ApiV1publicServicesIndexRoute,
  ApiV1publicShippingRoutesIndexRoute: ApiV1publicShippingRoutesIndexRoute,
  ApiV1publicSiteSettingsIndexRoute: ApiV1publicSiteSettingsIndexRoute,
  ApiV1publicSitemapIndexRoute: ApiV1publicSitemapIndexRoute,
  ApiV1publicTestimonialsIndexRoute: ApiV1publicTestimonialsIndexRoute,
  ApiV1publicTranslationsIndexRoute: ApiV1publicTranslationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
