/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MarketplacesRouteImport } from './routes/marketplaces'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangeRequestsRouteImport } from './routes/change-requests'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AgentJobsRouteImport } from './routes/agent-jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as PricingIndexRouteImport } from './routes/pricing.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as PricingUsRouteImport } from './routes/pricing.us'
import { Route as PricingHistoryRouteImport } from './routes/pricing.history'
import { Route as CareersApplicantsRouteImport } from './routes/careers.applicants'
import { Route as CareersJobIdRouteImport } from './routes/careers.$jobId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesRoute = MarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRequestsRoute = ChangeRequestsRouteImport.update({
  id: '/change-requests',
  path: '/change-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentJobsRoute = AgentJobsRouteImport.update({
  id: '/agent-jobs',
  path: '/agent-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PricingRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)
const PricingUsRoute = PricingUsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => PricingRoute,
} as any)
const PricingHistoryRoute = PricingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PricingRoute,
} as any)
const CareersApplicantsRoute = CareersApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => CareersRoute,
} as any)
const CareersJobIdRoute = CareersJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => CareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-jobs': typeof AgentJobsRoute
  '/audit': typeof AuditRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRouteWithChildren
  '/change-requests': typeof ChangeRequestsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/marketplaces': typeof MarketplacesRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sources': typeof SourcesRoute
  '/telegram': typeof TelegramRoute
  '/testimonials': typeof TestimonialsRoute
  '/users': typeof UsersRoute
  '/careers/$jobId': typeof CareersJobIdRoute
  '/careers/applicants': typeof CareersApplicantsRoute
  '/pricing/history': typeof PricingHistoryRoute
  '/pricing/us': typeof PricingUsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/careers/': typeof CareersIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-jobs': typeof AgentJobsRoute
  '/audit': typeof AuditRoute
  '/blogs': typeof BlogsRoute
  '/change-requests': typeof ChangeRequestsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/marketplaces': typeof MarketplacesRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/reviews': typeof ReviewsRoute
  '/sources': typeof SourcesRoute
  '/telegram': typeof TelegramRoute
  '/testimonials': typeof TestimonialsRoute
  '/users': typeof UsersRoute
  '/careers/$jobId': typeof CareersJobIdRoute
  '/careers/applicants': typeof CareersApplicantsRoute
  '/pricing/history': typeof PricingHistoryRoute
  '/pricing/us': typeof PricingUsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/careers': typeof CareersIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-jobs': typeof AgentJobsRoute
  '/audit': typeof AuditRoute
  '/blogs': typeof BlogsRoute
  '/careers': typeof CareersRouteWithChildren
  '/change-requests': typeof ChangeRequestsRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/history': typeof HistoryRoute
  '/landing': typeof LandingRoute
  '/marketplaces': typeof MarketplacesRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/pricing': typeof PricingRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sources': typeof SourcesRoute
  '/telegram': typeof TelegramRoute
  '/testimonials': typeof TestimonialsRoute
  '/users': typeof UsersRoute
  '/careers/$jobId': typeof CareersJobIdRoute
  '/careers/applicants': typeof CareersApplicantsRoute
  '/pricing/history': typeof PricingHistoryRoute
  '/pricing/us': typeof PricingUsRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/careers/': typeof CareersIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-jobs'
    | '/audit'
    | '/blogs'
    | '/careers'
    | '/change-requests'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/history'
    | '/landing'
    | '/marketplaces'
    | '/media'
    | '/policies'
    | '/pricing'
    | '/reviews'
    | '/services'
    | '/sources'
    | '/telegram'
    | '/testimonials'
    | '/users'
    | '/careers/$jobId'
    | '/careers/applicants'
    | '/pricing/history'
    | '/pricing/us'
    | '/services/$serviceId'
    | '/careers/'
    | '/pricing/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-jobs'
    | '/audit'
    | '/blogs'
    | '/change-requests'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/history'
    | '/landing'
    | '/marketplaces'
    | '/media'
    | '/policies'
    | '/reviews'
    | '/sources'
    | '/telegram'
    | '/testimonials'
    | '/users'
    | '/careers/$jobId'
    | '/careers/applicants'
    | '/pricing/history'
    | '/pricing/us'
    | '/services/$serviceId'
    | '/careers'
    | '/pricing'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/agent-jobs'
    | '/audit'
    | '/blogs'
    | '/careers'
    | '/change-requests'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/history'
    | '/landing'
    | '/marketplaces'
    | '/media'
    | '/policies'
    | '/pricing'
    | '/reviews'
    | '/services'
    | '/sources'
    | '/telegram'
    | '/testimonials'
    | '/users'
    | '/careers/$jobId'
    | '/careers/applicants'
    | '/pricing/history'
    | '/pricing/us'
    | '/services/$serviceId'
    | '/careers/'
    | '/pricing/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentJobsRoute: typeof AgentJobsRoute
  AuditRoute: typeof AuditRoute
  BlogsRoute: typeof BlogsRoute
  CareersRoute: typeof CareersRouteWithChildren
  ChangeRequestsRoute: typeof ChangeRequestsRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  HistoryRoute: typeof HistoryRoute
  LandingRoute: typeof LandingRoute
  MarketplacesRoute: typeof MarketplacesRoute
  MediaRoute: typeof MediaRoute
  PoliciesRoute: typeof PoliciesRoute
  PricingRoute: typeof PricingRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SourcesRoute: typeof SourcesRoute
  TelegramRoute: typeof TelegramRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces': {
      id: '/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof MarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-requests': {
      id: '/change-requests'
      path: '/change-requests'
      fullPath: '/change-requests'
      preLoaderRoute: typeof ChangeRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-jobs': {
      id: '/agent-jobs'
      path: '/agent-jobs'
      fullPath: '/agent-jobs'
      preLoaderRoute: typeof AgentJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof PricingRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/pricing/us': {
      id: '/pricing/us'
      path: '/us'
      fullPath: '/pricing/us'
      preLoaderRoute: typeof PricingUsRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/history': {
      id: '/pricing/history'
      path: '/history'
      fullPath: '/pricing/history'
      preLoaderRoute: typeof PricingHistoryRouteImport
      parentRoute: typeof PricingRoute
    }
    '/careers/applicants': {
      id: '/careers/applicants'
      path: '/applicants'
      fullPath: '/careers/applicants'
      preLoaderRoute: typeof CareersApplicantsRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$jobId': {
      id: '/careers/$jobId'
      path: '/$jobId'
      fullPath: '/careers/$jobId'
      preLoaderRoute: typeof CareersJobIdRouteImport
      parentRoute: typeof CareersRoute
    }
  }
}

interface CareersRouteChildren {
  CareersJobIdRoute: typeof CareersJobIdRoute
  CareersApplicantsRoute: typeof CareersApplicantsRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersJobIdRoute: CareersJobIdRoute,
  CareersApplicantsRoute: CareersApplicantsRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface PricingRouteChildren {
  PricingHistoryRoute: typeof PricingHistoryRoute
  PricingUsRoute: typeof PricingUsRoute
  PricingIndexRoute: typeof PricingIndexRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingHistoryRoute: PricingHistoryRoute,
  PricingUsRoute: PricingUsRoute,
  PricingIndexRoute: PricingIndexRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentJobsRoute: AgentJobsRoute,
  AuditRoute: AuditRoute,
  BlogsRoute: BlogsRoute,
  CareersRoute: CareersRouteWithChildren,
  ChangeRequestsRoute: ChangeRequestsRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  HistoryRoute: HistoryRoute,
  LandingRoute: LandingRoute,
  MarketplacesRoute: MarketplacesRoute,
  MediaRoute: MediaRoute,
  PoliciesRoute: PoliciesRoute,
  PricingRoute: PricingRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SourcesRoute: SourcesRoute,
  TelegramRoute: TelegramRoute,
  TestimonialsRoute: TestimonialsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
